package com.zacksimpson.emojis

// Auto-generated from the RN app's utils/emojiData.ts via scripts/convert-emoji-index.js — do not hand-edit.
// Part 5/13 of EMOJI_INDEX, split across files so each file's <clinit> stays under the JVM's 64KB method size limit.
internal val EMOJI_INDEX_PART_4: List<EmojiEntry> = listOf(
    EmojiEntry("🐳", "spouting whale", listOf("face", "spouting", "whale")),
    EmojiEntry("🐋", "whale", listOf("whale")),
    EmojiEntry("🐬", "dolphin", listOf("dolphin", "flipper")),
    EmojiEntry("🦭", "seal", listOf("sea lion", "seal")),
    EmojiEntry("🐟", "fish", listOf("fish", "Pisces", "zodiac")),
    EmojiEntry("🐠", "tropical fish", listOf("fish", "tropical")),
    EmojiEntry("🐡", "blowfish", listOf("blowfish", "fish")),
    EmojiEntry("🦈", "shark", listOf("fish", "shark")),
    EmojiEntry("🐙", "octopus", listOf("octopus")),
    EmojiEntry("🐚", "spiral shell", listOf("shell", "spiral")),
    EmojiEntry("🐌", "snail", listOf("snail")),
    EmojiEntry("🦋", "butterfly", listOf("butterfly", "insect", "pretty")),
    EmojiEntry("🐛", "bug", listOf("bug", "insect")),
    EmojiEntry("🐜", "ant", listOf("ant", "insect")),
    EmojiEntry("🐝", "honeybee", listOf("bee", "honeybee", "insect")),
    EmojiEntry("🪲", "beetle", listOf("beetle", "bug", "insect")),
    EmojiEntry("🐞", "lady beetle", listOf("beetle", "insect", "lady beetle", "ladybird", "ladybug")),
    EmojiEntry("🦗", "cricket", listOf("cricket", "grasshopper", "Orthoptera")),
    EmojiEntry("🪳", "cockroach", listOf("cockroach", "insect", "pest", "roach")),
    EmojiEntry("🕷", "spider", listOf("insect", "spider")),
    EmojiEntry("🕸", "spider web", listOf("spider", "web")),
    EmojiEntry("🦂", "scorpion", listOf("scorpio", "Scorpio", "scorpion", "zodiac")),
    EmojiEntry("🦟", "mosquito", listOf("disease", "fever", "malaria", "mosquito", "pest", "virus")),
    EmojiEntry("🪰", "fly", listOf("disease", "fly", "maggot", "pest", "rotting")),
    EmojiEntry("🪱", "worm", listOf("annelid", "earthworm", "parasite", "worm")),
    EmojiEntry("🦠", "microbe", listOf("amoeba", "bacteria", "microbe", "virus")),
    EmojiEntry("💐", "bouquet", listOf("bouquet", "flower")),
    EmojiEntry("🌸", "cherry blossom", listOf("blossom", "cherry", "flower")),
    EmojiEntry("💮", "white flower", listOf("flower", "white flower")),
    EmojiEntry("🏵", "rosette", listOf("plant", "rosette")),
    EmojiEntry("🌹", "rose", listOf("flower", "rose")),
    EmojiEntry("🥀", "wilted flower", listOf("flower", "wilted")),
    EmojiEntry("🌺", "hibiscus", listOf("flower", "hibiscus")),
    EmojiEntry("🌻", "sunflower", listOf("flower", "sun", "sunflower")),
    EmojiEntry("🌼", "blossom", listOf("blossom", "flower")),
    EmojiEntry("🌷", "tulip", listOf("flower", "tulip")),
    EmojiEntry("🌱", "seedling", listOf("seedling", "young")),
    EmojiEntry("🪴", "potted plant", listOf("boring", "grow", "house", "nurturing", "plant", "potted plant", "useless")),
    EmojiEntry("🌲", "evergreen tree", listOf("evergreen tree", "tree")),
    EmojiEntry("🌳", "deciduous tree", listOf("deciduous", "shedding", "tree")),
    EmojiEntry("🌴", "palm tree", listOf("palm", "tree")),
    EmojiEntry("🌵", "cactus", listOf("cactus", "plant")),
    EmojiEntry("🌾", "sheaf of rice", listOf("ear", "grain", "rice", "sheaf of rice")),
    EmojiEntry("🌿", "herb", listOf("herb", "leaf")),
    EmojiEntry("☘", "shamrock", listOf("plant", "shamrock")),
    EmojiEntry("🍀", "four leaf clover", listOf("4", "clover", "four", "four-leaf clover", "leaf")),
    EmojiEntry("🍁", "maple leaf", listOf("falling", "leaf", "maple")),
    EmojiEntry("🍂", "fallen leaf", listOf("fallen leaf", "falling", "leaf")),
    EmojiEntry("🍃", "leaf fluttering in wind", listOf("blow", "flutter", "leaf", "leaf fluttering in wind", "wind")),
    EmojiEntry("🍇", "grapes", listOf("fruit", "grape", "grapes")),
    EmojiEntry("🍈", "melon", listOf("fruit", "melon")),
    EmojiEntry("🍉", "watermelon", listOf("fruit", "watermelon")),
    EmojiEntry("🍊", "tangerine", listOf("fruit", "orange", "tangerine")),
    EmojiEntry("🍋", "lemon", listOf("citrus", "fruit", "lemon")),
    EmojiEntry("🍌", "banana", listOf("banana", "fruit")),
    EmojiEntry("🍍", "pineapple", listOf("fruit", "pineapple")),
    EmojiEntry("🥭", "mango", listOf("fruit", "mango", "tropical")),
    EmojiEntry("🍎", "red apple", listOf("apple", "fruit", "red")),
    EmojiEntry("🍏", "green apple", listOf("apple", "fruit", "green")),
    EmojiEntry("🍐", "pear", listOf("fruit", "pear")),
    EmojiEntry("🍑", "peach", listOf("fruit", "peach")),
    EmojiEntry("🍒", "cherries", listOf("berries", "cherries", "cherry", "fruit", "red")),
    EmojiEntry("🍓", "strawberry", listOf("berry", "fruit", "strawberry")),
    EmojiEntry("🫐", "blueberries", listOf("berry", "bilberry", "blue", "blueberries", "blueberry")),
    EmojiEntry("🥝", "kiwi fruit", listOf("food", "fruit", "kiwi")),
    EmojiEntry("🍅", "tomato", listOf("fruit", "tomato", "vegetable")),
    EmojiEntry("🫒", "olive", listOf("food", "olive")),
    EmojiEntry("🥥", "coconut", listOf("coconut", "palm", "piña colada")),
    EmojiEntry("🥑", "avocado", listOf("avocado", "food", "fruit")),
    EmojiEntry("🍆", "eggplant", listOf("aubergine", "eggplant", "vegetable")),
    EmojiEntry("🥔", "potato", listOf("food", "potato", "vegetable")),
    EmojiEntry("🥕", "carrot", listOf("carrot", "food", "vegetable")),
    EmojiEntry("🌽", "ear of corn", listOf("corn", "ear", "ear of corn", "maize", "maze")),
    EmojiEntry("🌶", "hot pepper", listOf("hot", "pepper")),
    EmojiEntry("🫑", "bell pepper", listOf("bell pepper", "capsicum", "pepper", "vegetable")),
    EmojiEntry("🥒", "cucumber", listOf("cucumber", "food", "pickle", "vegetable")),
    EmojiEntry("🥬", "leafy green", listOf("bok choy", "cabbage", "kale", "leafy green", "lettuce")),
    EmojiEntry("🥦", "broccoli", listOf("broccoli", "wild cabbage")),
    EmojiEntry("🧄", "garlic", listOf("flavoring", "garlic")),
    EmojiEntry("🧅", "onion", listOf("flavoring", "onion")),
    EmojiEntry("🍄", "mushroom", listOf("mushroom", "toadstool")),
    EmojiEntry("🥜", "peanuts", listOf("food", "nut", "peanut", "peanuts", "vegetable")),
    EmojiEntry("🌰", "chestnut", listOf("chestnut", "plant")),
    EmojiEntry("🍞", "bread", listOf("bread", "loaf")),
    EmojiEntry("🥐", "croissant", listOf("bread", "breakfast", "croissant", "food", "french", "roll")),
    EmojiEntry("🥖", "baguette bread", listOf("baguette", "bread", "food", "french")),
    EmojiEntry("🫓", "flatbread", listOf("arepa", "flatbread", "lavash", "naan", "pita")),
    EmojiEntry("🥨", "pretzel", listOf("pretzel", "twisted", "convoluted")),
    EmojiEntry("🥯", "bagel", listOf("bagel", "bakery", "breakfast", "schmear")),
    EmojiEntry("🥞", "pancakes", listOf("breakfast", "crêpe", "food", "hotcake", "pancake", "pancakes")),
    EmojiEntry("🧇", "waffle", listOf("breakfast", "indecisive", "iron", "waffle")),
    EmojiEntry("🧀", "cheese wedge", listOf("cheese", "cheese wedge")),
    EmojiEntry("🍖", "meat on bone", listOf("bone", "meat", "meat on bone")),
    EmojiEntry("🍗", "poultry leg", listOf("bone", "chicken", "drumstick", "leg", "poultry")),
    EmojiEntry("🥩", "cut of meat", listOf("chop", "cut of meat", "lambchop", "porkchop", "steak")),
    EmojiEntry("🥓", "bacon", listOf("bacon", "breakfast", "food", "meat")),
    EmojiEntry("🍔", "hamburger", listOf("burger", "hamburger")),
    EmojiEntry("🍟", "french fries", listOf("french", "fries")),
    EmojiEntry("🍕", "pizza", listOf("cheese", "pizza", "slice")),
    EmojiEntry("🌭", "hot dog", listOf("frankfurter", "hot dog", "hotdog", "sausage")),
    EmojiEntry("🥪", "sandwich", listOf("bread", "sandwich")),
    EmojiEntry("🌮", "taco", listOf("mexican", "taco")),
    EmojiEntry("🌯", "burrito", listOf("burrito", "mexican", "wrap")),
    EmojiEntry("🫔", "tamale", listOf("mexican", "tamale", "wrapped")),
    EmojiEntry("🥙", "stuffed flatbread", listOf("falafel", "flatbread", "food", "gyro", "kebab", "stuffed")),
    EmojiEntry("🧆", "falafel", listOf("chickpea", "falafel", "meatball")),
    EmojiEntry("🥚", "egg", listOf("breakfast", "egg", "food")),
    EmojiEntry("🍳", "cooking", listOf("breakfast", "cooking", "egg", "frying", "pan")),
    EmojiEntry("🥘", "shallow pan of food", listOf("casserole", "food", "paella", "pan", "shallow", "shallow pan of food")),
    EmojiEntry("🍲", "pot of food", listOf("pot", "pot of food", "stew")),
    EmojiEntry("🫕", "fondue", listOf("cheese", "chocolate", "fondue", "melted", "pot", "Swiss")),
    EmojiEntry("🥣", "bowl with spoon", listOf("bowl with spoon", "breakfast", "cereal", "congee", "oatmeal", "porridge")),
    EmojiEntry("🥗", "green salad", listOf("food", "green", "salad")),
    EmojiEntry("🍿", "popcorn", listOf("popcorn")),
    EmojiEntry("🧈", "butter", listOf("butter", "dairy")),
    EmojiEntry("🧂", "salt", listOf("condiment", "salt", "shaker")),
    EmojiEntry("🥫", "canned food", listOf("can", "canned food")),
    EmojiEntry("🍱", "bento box", listOf("bento", "box")),
    EmojiEntry("🍘", "rice cracker", listOf("cracker", "rice")),
    EmojiEntry("🍙", "rice ball", listOf("ball", "Japanese", "rice")),
    EmojiEntry("🍚", "cooked rice", listOf("cooked", "rice")),
    EmojiEntry("🍛", "curry rice", listOf("curry", "rice")),
    EmojiEntry("🍜", "steaming bowl", listOf("bowl", "noodle", "ramen", "steaming")),
    EmojiEntry("🍝", "spaghetti", listOf("pasta", "spaghetti")),
    EmojiEntry("🍠", "roasted sweet potato", listOf("potato", "roasted", "sweet")),
    EmojiEntry("🍢", "oden", listOf("kebab", "oden", "seafood", "skewer", "stick")),
    EmojiEntry("🍣", "sushi", listOf("sushi")),
    EmojiEntry("🍤", "fried shrimp", listOf("fried", "prawn", "shrimp", "tempura")),
    EmojiEntry("🍥", "fish cake with swirl", listOf("cake", "fish", "fish cake with swirl", "pastry", "swirl")),
    EmojiEntry("🥮", "moon cake", listOf("autumn", "festival", "moon cake", "yuèb?ng")),
    EmojiEntry("🍡", "dango", listOf("dango", "dessert", "Japanese", "skewer", "stick", "sweet")),
    EmojiEntry("🥟", "dumpling", listOf("dumpling", "empanada", "gy?za", "jiaozi", "pierogi", "potsticker")),
    EmojiEntry("🥠", "fortune cookie", listOf("fortune cookie", "prophecy")),
    EmojiEntry("🥡", "takeout box", listOf("oyster pail", "takeout box")),
    EmojiEntry("🦀", "crab", listOf("Cancer", "crab", "zodiac")),
    EmojiEntry("🦞", "lobster", listOf("bisque", "claws", "lobster", "seafood")),
    EmojiEntry("🦐", "shrimp", listOf("food", "shellfish", "shrimp", "small")),
    EmojiEntry("🦑", "squid", listOf("food", "molusc", "squid")),
    EmojiEntry("🦪", "oyster", listOf("diving", "oyster", "pearl")),
    EmojiEntry("🍦", "soft ice cream", listOf("cream", "dessert", "ice", "icecream", "soft", "sweet")),
    EmojiEntry("🍧", "shaved ice", listOf("dessert", "ice", "shaved", "sweet")),
    EmojiEntry("🍨", "ice cream", listOf("cream", "dessert", "ice", "sweet")),
    EmojiEntry("🍩", "doughnut", listOf("breakfast", "dessert", "donut", "doughnut", "sweet")),
    EmojiEntry("🍪", "cookie", listOf("cookie", "dessert", "sweet")),
    EmojiEntry("🎂", "birthday cake", listOf("birthday", "cake", "celebration", "dessert", "pastry", "sweet")),
    EmojiEntry("🍰", "shortcake", listOf("cake", "dessert", "pastry", "shortcake", "slice", "sweet")),
    EmojiEntry("🧁", "cupcake", listOf("bakery", "cupcake", "sweet")),
    EmojiEntry("🥧", "pie", listOf("filling", "pastry", "pie", "fruit", "meat")),
    EmojiEntry("🍫", "chocolate bar", listOf("bar", "chocolate", "dessert", "sweet")),
    EmojiEntry("🍬", "candy", listOf("candy", "dessert", "sweet")),
)
