package com.zacksimpson.emojis

// Auto-generated from the RN app's utils/emojiData.ts via scripts/convert-emoji-index.js — do not hand-edit.
// Part 11/13 of EMOJI_INDEX, split across files so each file's <clinit> stays under the JVM's 64KB method size limit.
internal val EMOJI_INDEX_PART_10: List<EmojiEntry> = listOf(
    EmojiEntry("🈯", "Japanese reserved button", listOf("reserved", "ideograph", "Japanese", "Japanese reserved button", "?")),
    EmojiEntry("🉐", "Japanese bargain button", listOf("bargain", "ideograph", "Japanese", "Japanese bargain button", "?")),
    EmojiEntry("🈹", "Japanese discount button", listOf("discount", "ideograph", "Japanese", "Japanese discount button", "?")),
    EmojiEntry("🈚", "Japanese free of charge button", listOf("free of charge", "ideograph", "Japanese", "Japanese free of charge button", "?")),
    EmojiEntry("🈲", "Japanese prohibited button", listOf("prohibited", "ideograph", "Japanese", "Japanese prohibited button", "?")),
    EmojiEntry("🉑", "Japanese acceptable button", listOf("acceptable", "ideograph", "Japanese", "Japanese acceptable button", "?")),
    EmojiEntry("🈸", "Japanese application button", listOf("application", "ideograph", "Japanese", "Japanese application button", "?")),
    EmojiEntry("🈴", "Japanese passing grade button", listOf("passing grade", "ideograph", "Japanese", "Japanese passing grade button", "?")),
    EmojiEntry("🈳", "Japanese vacancy button", listOf("vacancy", "ideograph", "Japanese", "Japanese vacancy button", "?")),
    EmojiEntry("㊗", "Japanese congratulations button", listOf("congratulations", "ideograph", "Japanese", "Japanese congratulations button", "?")),
    EmojiEntry("㊙", "Japanese secret button", listOf("secret", "ideograph", "Japanese", "Japanese secret button", "?")),
    EmojiEntry("🈺", "Japanese open for business button", listOf("open for business", "ideograph", "Japanese", "Japanese open for business button", "?")),
    EmojiEntry("🈵", "Japanese no vacancy button", listOf("no vacancy", "ideograph", "Japanese", "Japanese no vacancy button", "?")),
    EmojiEntry("🔴", "red circle", listOf("circle", "geometric", "red")),
    EmojiEntry("🟠", "orange circle", listOf("circle", "orange")),
    EmojiEntry("🟡", "yellow circle", listOf("circle", "yellow")),
    EmojiEntry("🟢", "green circle", listOf("circle", "green")),
    EmojiEntry("🔵", "blue circle", listOf("blue", "circle", "geometric")),
    EmojiEntry("🟣", "purple circle", listOf("circle", "purple")),
    EmojiEntry("🟤", "brown circle", listOf("brown", "circle")),
    EmojiEntry("⚫", "black circle", listOf("black circle", "circle", "geometric")),
    EmojiEntry("⚪", "white circle", listOf("circle", "geometric", "white circle")),
    EmojiEntry("🟥", "red square", listOf("red", "square")),
    EmojiEntry("🟧", "orange square", listOf("orange", "square")),
    EmojiEntry("🟨", "yellow square", listOf("square", "yellow")),
    EmojiEntry("🟩", "green square", listOf("green", "square")),
    EmojiEntry("🟦", "blue square", listOf("blue", "square")),
    EmojiEntry("🟪", "purple square", listOf("purple", "square")),
    EmojiEntry("🟫", "brown square", listOf("brown", "square")),
    EmojiEntry("⬛", "black large square", listOf("black large square", "geometric", "square")),
    EmojiEntry("⬜", "white large square", listOf("geometric", "square", "white large square")),
    EmojiEntry("◼", "black medium square", listOf("black medium square", "geometric", "square")),
    EmojiEntry("◻", "white medium square", listOf("geometric", "square", "white medium square")),
    EmojiEntry("◾", "black medium-small square", listOf("black medium-small square", "geometric", "square")),
    EmojiEntry("◽", "white medium-small square", listOf("geometric", "square", "white medium-small square")),
    EmojiEntry("▪", "black small square", listOf("black small square", "geometric", "square")),
    EmojiEntry("▫", "white small square", listOf("geometric", "square", "white small square")),
    EmojiEntry("🔶", "large orange diamond", listOf("diamond", "geometric", "large orange diamond", "orange")),
    EmojiEntry("🔷", "large blue diamond", listOf("blue", "diamond", "geometric", "large blue diamond")),
    EmojiEntry("🔸", "small orange diamond", listOf("diamond", "geometric", "orange", "small orange diamond")),
    EmojiEntry("🔹", "small blue diamond", listOf("blue", "diamond", "geometric", "small blue diamond")),
    EmojiEntry("🔺", "red triangle pointed up", listOf("geometric", "red", "red triangle pointed up")),
    EmojiEntry("🔻", "red triangle pointed down", listOf("down", "geometric", "red", "red triangle pointed down")),
    EmojiEntry("💠", "diamond with a dot", listOf("comic", "diamond", "diamond with a dot", "geometric", "inside")),
    EmojiEntry("🔘", "radio button", listOf("button", "geometric", "radio")),
    EmojiEntry("🔳", "white square button", listOf("button", "geometric", "outlined", "square", "white square button")),
    EmojiEntry("🔲", "black square button", listOf("black square button", "button", "geometric", "square")),
    EmojiEntry("🏁", "chequered flag", listOf("checkered", "chequered", "chequered flag", "racing")),
    EmojiEntry("🚩", "triangular flag", listOf("post", "triangular flag")),
    EmojiEntry("🎌", "crossed flags", listOf("celebration", "cross", "crossed", "crossed flags", "Japanese")),
    EmojiEntry("🏴", "black flag", listOf("black flag", "waving")),
    EmojiEntry("🏳", "white flag", listOf("waving", "white flag")),
    EmojiEntry("🏳️‍🌈", "rainbow flag", listOf("pride", "rainbow", "rainbow flag")),
    EmojiEntry("🏳️‍⚧️", "transgender flag", listOf("flag", "light blue", "pink", "transgender", "white")),
    EmojiEntry("🏴‍☠️", "pirate flag", listOf("Jolly Roger", "pirate", "pirate flag", "plunder", "treasure")),
    EmojiEntry("🇦🇨", "flag: Ascension Island", listOf("flag")),
    EmojiEntry("🇦🇩", "flag: Andorra", listOf("flag")),
    EmojiEntry("🇦🇪", "flag: United Arab Emirates", listOf("flag")),
    EmojiEntry("🇦🇫", "flag: Afghanistan", listOf("flag")),
    EmojiEntry("🇦🇬", "flag: Antigua & Barbuda", listOf("flag")),
    EmojiEntry("🇦🇮", "flag: Anguilla", listOf("flag")),
    EmojiEntry("🇦🇱", "flag: Albania", listOf("flag")),
    EmojiEntry("🇦🇲", "flag: Armenia", listOf("flag")),
    EmojiEntry("🇦🇴", "flag: Angola", listOf("flag")),
    EmojiEntry("🇦🇶", "flag: Antarctica", listOf("flag")),
    EmojiEntry("🇦🇷", "flag: Argentina", listOf("flag")),
    EmojiEntry("🇦🇸", "flag: American Samoa", listOf("flag")),
    EmojiEntry("🇦🇹", "flag: Austria", listOf("flag")),
    EmojiEntry("🇦🇺", "flag: Australia", listOf("flag")),
    EmojiEntry("🇦🇼", "flag: Aruba", listOf("flag")),
    EmojiEntry("🇦🇽", "flag: Åland Islands", listOf("flag")),
    EmojiEntry("🇦🇿", "flag: Azerbaijan", listOf("flag")),
    EmojiEntry("🇧🇦", "flag: Bosnia & Herzegovina", listOf("flag")),
    EmojiEntry("🇧🇧", "flag: Barbados", listOf("flag")),
    EmojiEntry("🇧🇩", "flag: Bangladesh", listOf("flag")),
    EmojiEntry("🇧🇪", "flag: Belgium", listOf("flag")),
    EmojiEntry("🇧🇫", "flag: Burkina Faso", listOf("flag")),
    EmojiEntry("🇧🇬", "flag: Bulgaria", listOf("flag")),
    EmojiEntry("🇧🇭", "flag: Bahrain", listOf("flag")),
    EmojiEntry("🇧🇮", "flag: Burundi", listOf("flag")),
    EmojiEntry("🇧🇯", "flag: Benin", listOf("flag")),
    EmojiEntry("🇧🇱", "flag: St. Barthélemy", listOf("flag")),
    EmojiEntry("🇧🇲", "flag: Bermuda", listOf("flag")),
    EmojiEntry("🇧🇳", "flag: Brunei", listOf("flag")),
    EmojiEntry("🇧🇴", "flag: Bolivia", listOf("flag")),
    EmojiEntry("🇧🇶", "flag: Caribbean Netherlands", listOf("flag")),
    EmojiEntry("🇧🇷", "flag: Brazil", listOf("flag")),
    EmojiEntry("🇧🇸", "flag: Bahamas", listOf("flag")),
    EmojiEntry("🇧🇹", "flag: Bhutan", listOf("flag")),
    EmojiEntry("🇧🇻", "flag: Bouvet Island", listOf("flag")),
    EmojiEntry("🇧🇼", "flag: Botswana", listOf("flag")),
    EmojiEntry("🇧🇾", "flag: Belarus", listOf("flag")),
    EmojiEntry("🇧🇿", "flag: Belize", listOf("flag")),
    EmojiEntry("🇨🇦", "flag: Canada", listOf("flag")),
    EmojiEntry("🇨🇨", "flag: Cocos (Keeling) Islands", listOf("flag")),
    EmojiEntry("🇨🇩", "flag: Congo - Kinshasa", listOf("flag")),
    EmojiEntry("🇨🇫", "flag: Central African Republic", listOf("flag")),
    EmojiEntry("🇨🇬", "flag: Congo - Brazzaville", listOf("flag")),
    EmojiEntry("🇨🇭", "flag: Switzerland", listOf("flag")),
    EmojiEntry("🇨🇮", "flag: Côte dIvoire", listOf("flag")),
    EmojiEntry("🇨🇰", "flag: Cook Islands", listOf("flag")),
    EmojiEntry("🇨🇱", "flag: Chile", listOf("flag")),
    EmojiEntry("🇨🇲", "flag: Cameroon", listOf("flag")),
    EmojiEntry("🇨🇳", "flag: China", listOf("flag")),
    EmojiEntry("🇨🇴", "flag: Colombia", listOf("flag")),
    EmojiEntry("🇨🇵", "flag: Clipperton Island", listOf("flag")),
    EmojiEntry("🇨🇷", "flag: Costa Rica", listOf("flag")),
    EmojiEntry("🇨🇺", "flag: Cuba", listOf("flag")),
    EmojiEntry("🇨🇻", "flag: Cape Verde", listOf("flag")),
    EmojiEntry("🇨🇼", "flag: Curaçao", listOf("flag")),
    EmojiEntry("🇨🇽", "flag: Christmas Island", listOf("flag")),
    EmojiEntry("🇨🇾", "flag: Cyprus", listOf("flag")),
    EmojiEntry("🇨🇿", "flag: Czechia", listOf("flag")),
    EmojiEntry("🇩🇪", "flag: Germany", listOf("flag")),
    EmojiEntry("🇩🇬", "flag: Diego Garcia", listOf("flag")),
    EmojiEntry("🇩🇯", "flag: Djibouti", listOf("flag")),
    EmojiEntry("🇩🇰", "flag: Denmark", listOf("flag")),
    EmojiEntry("🇩🇲", "flag: Dominica", listOf("flag")),
    EmojiEntry("🇩🇴", "flag: Dominican Republic", listOf("flag")),
    EmojiEntry("🇩🇿", "flag: Algeria", listOf("flag")),
    EmojiEntry("🇪🇦", "flag: Ceuta & Melilla", listOf("flag")),
    EmojiEntry("🇪🇨", "flag: Ecuador", listOf("flag")),
    EmojiEntry("🇪🇪", "flag: Estonia", listOf("flag")),
    EmojiEntry("🇪🇬", "flag: Egypt", listOf("flag")),
    EmojiEntry("🇪🇭", "flag: Western Sahara", listOf("flag")),
    EmojiEntry("🇪🇷", "flag: Eritrea", listOf("flag")),
    EmojiEntry("🇪🇸", "flag: Spain", listOf("flag")),
    EmojiEntry("🇪🇹", "flag: Ethiopia", listOf("flag")),
    EmojiEntry("🇪🇺", "flag: European Union", listOf("flag")),
    EmojiEntry("🇫🇮", "flag: Finland", listOf("flag")),
    EmojiEntry("🇫🇯", "flag: Fiji", listOf("flag")),
    EmojiEntry("🇫🇰", "flag: Falkland Islands", listOf("flag")),
    EmojiEntry("🇫🇲", "flag: Micronesia", listOf("flag")),
    EmojiEntry("🇫🇴", "flag: Faroe Islands", listOf("flag")),
    EmojiEntry("🇫🇷", "flag: France", listOf("flag")),
    EmojiEntry("🇬🇦", "flag: Gabon", listOf("flag")),
    EmojiEntry("🇬🇧", "flag: United Kingdom", listOf("flag")),
    EmojiEntry("🇬🇩", "flag: Grenada", listOf("flag")),
    EmojiEntry("🇬🇪", "flag: Georgia", listOf("flag")),
    EmojiEntry("🇬🇫", "flag: French Guiana", listOf("flag")),
    EmojiEntry("🇬🇬", "flag: Guernsey", listOf("flag")),
    EmojiEntry("🇬🇭", "flag: Ghana", listOf("flag")),
    EmojiEntry("🇬🇮", "flag: Gibraltar", listOf("flag")),
    EmojiEntry("🇬🇱", "flag: Greenland", listOf("flag")),
    EmojiEntry("🇬🇲", "flag: Gambia", listOf("flag")),
    EmojiEntry("🇬🇳", "flag: Guinea", listOf("flag")),
    EmojiEntry("🇬🇵", "flag: Guadeloupe", listOf("flag")),
    EmojiEntry("🇬🇶", "flag: Equatorial Guinea", listOf("flag")),
    EmojiEntry("🇬🇷", "flag: Greece", listOf("flag")),
    EmojiEntry("🇬🇸", "flag: South Georgia & South Sandwich Islands", listOf("flag")),
)
