package com.zacksimpson.emojis

// Auto-generated from the RN app's utils/emojiData.ts via scripts/convert-emoji-index.js — do not hand-edit.
// Part 12/13 of EMOJI_INDEX, split across files so each file's <clinit> stays under the JVM's 64KB method size limit.
internal val EMOJI_INDEX_PART_11: List<EmojiEntry> = listOf(
    EmojiEntry("🇬🇹", "flag: Guatemala", listOf("flag")),
    EmojiEntry("🇬🇺", "flag: Guam", listOf("flag")),
    EmojiEntry("🇬🇼", "flag: Guinea-Bissau", listOf("flag")),
    EmojiEntry("🇬🇾", "flag: Guyana", listOf("flag")),
    EmojiEntry("🇭🇰", "flag: Hong Kong SAR China", listOf("flag")),
    EmojiEntry("🇭🇲", "flag: Heard & McDonald Islands", listOf("flag")),
    EmojiEntry("🇭🇳", "flag: Honduras", listOf("flag")),
    EmojiEntry("🇭🇷", "flag: Croatia", listOf("flag")),
    EmojiEntry("🇭🇹", "flag: Haiti", listOf("flag")),
    EmojiEntry("🇭🇺", "flag: Hungary", listOf("flag")),
    EmojiEntry("🇮🇨", "flag: Canary Islands", listOf("flag")),
    EmojiEntry("🇮🇩", "flag: Indonesia", listOf("flag")),
    EmojiEntry("🇮🇪", "flag: Ireland", listOf("flag")),
    EmojiEntry("🇮🇱", "flag: Israel", listOf("flag")),
    EmojiEntry("🇮🇲", "flag: Isle of Man", listOf("flag")),
    EmojiEntry("🇮🇳", "flag: India", listOf("flag")),
    EmojiEntry("🇮🇴", "flag: British Indian Ocean Territory", listOf("flag")),
    EmojiEntry("🇮🇶", "flag: Iraq", listOf("flag")),
    EmojiEntry("🇮🇷", "flag: Iran", listOf("flag")),
    EmojiEntry("🇮🇸", "flag: Iceland", listOf("flag")),
    EmojiEntry("🇮🇹", "flag: Italy", listOf("flag")),
    EmojiEntry("🇯🇪", "flag: Jersey", listOf("flag")),
    EmojiEntry("🇯🇲", "flag: Jamaica", listOf("flag")),
    EmojiEntry("🇯🇴", "flag: Jordan", listOf("flag")),
    EmojiEntry("🇯🇵", "flag: Japan", listOf("flag")),
    EmojiEntry("🇰🇪", "flag: Kenya", listOf("flag")),
    EmojiEntry("🇰🇬", "flag: Kyrgyzstan", listOf("flag")),
    EmojiEntry("🇰🇭", "flag: Cambodia", listOf("flag")),
    EmojiEntry("🇰🇮", "flag: Kiribati", listOf("flag")),
    EmojiEntry("🇰🇲", "flag: Comoros", listOf("flag")),
    EmojiEntry("🇰🇳", "flag: St. Kitts & Nevis", listOf("flag")),
    EmojiEntry("🇰🇵", "flag: North Korea", listOf("flag")),
    EmojiEntry("🇰🇷", "flag: South Korea", listOf("flag")),
    EmojiEntry("🇰🇼", "flag: Kuwait", listOf("flag")),
    EmojiEntry("🇰🇾", "flag: Cayman Islands", listOf("flag")),
    EmojiEntry("🇰🇿", "flag: Kazakhstan", listOf("flag")),
    EmojiEntry("🇱🇦", "flag: Laos", listOf("flag")),
    EmojiEntry("🇱🇧", "flag: Lebanon", listOf("flag")),
    EmojiEntry("🇱🇨", "flag: St. Lucia", listOf("flag")),
    EmojiEntry("🇱🇮", "flag: Liechtenstein", listOf("flag")),
    EmojiEntry("🇱🇰", "flag: Sri Lanka", listOf("flag")),
    EmojiEntry("🇱🇷", "flag: Liberia", listOf("flag")),
    EmojiEntry("🇱🇸", "flag: Lesotho", listOf("flag")),
    EmojiEntry("🇱🇹", "flag: Lithuania", listOf("flag")),
    EmojiEntry("🇱🇺", "flag: Luxembourg", listOf("flag")),
    EmojiEntry("🇱🇻", "flag: Latvia", listOf("flag")),
    EmojiEntry("🇱🇾", "flag: Libya", listOf("flag")),
    EmojiEntry("🇲🇦", "flag: Morocco", listOf("flag")),
    EmojiEntry("🇲🇨", "flag: Monaco", listOf("flag")),
    EmojiEntry("🇲🇩", "flag: Moldova", listOf("flag")),
    EmojiEntry("🇲🇪", "flag: Montenegro", listOf("flag")),
    EmojiEntry("🇲🇫", "flag: St. Martin", listOf("flag")),
    EmojiEntry("🇲🇬", "flag: Madagascar", listOf("flag")),
    EmojiEntry("🇲🇭", "flag: Marshall Islands", listOf("flag")),
    EmojiEntry("🇲🇰", "flag: North Macedonia", listOf("flag")),
    EmojiEntry("🇲🇱", "flag: Mali", listOf("flag")),
    EmojiEntry("🇲🇲", "flag: Myanmar (Burma)", listOf("flag")),
    EmojiEntry("🇲🇳", "flag: Mongolia", listOf("flag")),
    EmojiEntry("🇲🇴", "flag: Macao SAR China", listOf("flag")),
    EmojiEntry("🇲🇵", "flag: Northern Mariana Islands", listOf("flag")),
    EmojiEntry("🇲🇶", "flag: Martinique", listOf("flag")),
    EmojiEntry("🇲🇷", "flag: Mauritania", listOf("flag")),
    EmojiEntry("🇲🇸", "flag: Montserrat", listOf("flag")),
    EmojiEntry("🇲🇹", "flag: Malta", listOf("flag")),
    EmojiEntry("🇲🇺", "flag: Mauritius", listOf("flag")),
    EmojiEntry("🇲🇻", "flag: Maldives", listOf("flag")),
    EmojiEntry("🇲🇼", "flag: Malawi", listOf("flag")),
    EmojiEntry("🇲🇽", "flag: Mexico", listOf("flag")),
    EmojiEntry("🇲🇾", "flag: Malaysia", listOf("flag")),
    EmojiEntry("🇲🇿", "flag: Mozambique", listOf("flag")),
    EmojiEntry("🇳🇦", "flag: Namibia", listOf("flag")),
    EmojiEntry("🇳🇨", "flag: New Caledonia", listOf("flag")),
    EmojiEntry("🇳🇪", "flag: Niger", listOf("flag")),
    EmojiEntry("🇳🇫", "flag: Norfolk Island", listOf("flag")),
    EmojiEntry("🇳🇬", "flag: Nigeria", listOf("flag")),
    EmojiEntry("🇳🇮", "flag: Nicaragua", listOf("flag")),
    EmojiEntry("🇳🇱", "flag: Netherlands", listOf("flag")),
    EmojiEntry("🇳🇴", "flag: Norway", listOf("flag")),
    EmojiEntry("🇳🇵", "flag: Nepal", listOf("flag")),
    EmojiEntry("🇳🇷", "flag: Nauru", listOf("flag")),
    EmojiEntry("🇳🇺", "flag: Niue", listOf("flag")),
    EmojiEntry("🇳🇿", "flag: New Zealand", listOf("flag")),
    EmojiEntry("🇴🇲", "flag: Oman", listOf("flag")),
    EmojiEntry("🇵🇦", "flag: Panama", listOf("flag")),
    EmojiEntry("🇵🇪", "flag: Peru", listOf("flag")),
    EmojiEntry("🇵🇫", "flag: French Polynesia", listOf("flag")),
    EmojiEntry("🇵🇬", "flag: Papua New Guinea", listOf("flag")),
    EmojiEntry("🇵🇭", "flag: Philippines", listOf("flag")),
    EmojiEntry("🇵🇰", "flag: Pakistan", listOf("flag")),
    EmojiEntry("🇵🇱", "flag: Poland", listOf("flag")),
    EmojiEntry("🇵🇲", "flag: St. Pierre & Miquelon", listOf("flag")),
    EmojiEntry("🇵🇳", "flag: Pitcairn Islands", listOf("flag")),
    EmojiEntry("🇵🇷", "flag: Puerto Rico", listOf("flag")),
    EmojiEntry("🇵🇸", "flag: Palestinian Territories", listOf("flag")),
    EmojiEntry("🇵🇹", "flag: Portugal", listOf("flag")),
    EmojiEntry("🇵🇼", "flag: Palau", listOf("flag")),
    EmojiEntry("🇵🇾", "flag: Paraguay", listOf("flag")),
    EmojiEntry("🇶🇦", "flag: Qatar", listOf("flag")),
    EmojiEntry("🇷🇪", "flag: Réunion", listOf("flag")),
    EmojiEntry("🇷🇴", "flag: Romania", listOf("flag")),
    EmojiEntry("🇷🇸", "flag: Serbia", listOf("flag")),
    EmojiEntry("🇷🇺", "flag: Russia", listOf("flag")),
    EmojiEntry("🇷🇼", "flag: Rwanda", listOf("flag")),
    EmojiEntry("🇸🇦", "flag: Saudi Arabia", listOf("flag")),
    EmojiEntry("🇸🇧", "flag: Solomon Islands", listOf("flag")),
    EmojiEntry("🇸🇨", "flag: Seychelles", listOf("flag")),
    EmojiEntry("🇸🇩", "flag: Sudan", listOf("flag")),
    EmojiEntry("🇸🇪", "flag: Sweden", listOf("flag")),
    EmojiEntry("🇸🇬", "flag: Singapore", listOf("flag")),
    EmojiEntry("🇸🇭", "flag: St. Helena", listOf("flag")),
    EmojiEntry("🇸🇮", "flag: Slovenia", listOf("flag")),
    EmojiEntry("🇸🇯", "flag: Svalbard & Jan Mayen", listOf("flag")),
    EmojiEntry("🇸🇰", "flag: Slovakia", listOf("flag")),
    EmojiEntry("🇸🇱", "flag: Sierra Leone", listOf("flag")),
    EmojiEntry("🇸🇲", "flag: San Marino", listOf("flag")),
    EmojiEntry("🇸🇳", "flag: Senegal", listOf("flag")),
    EmojiEntry("🇸🇴", "flag: Somalia", listOf("flag")),
    EmojiEntry("🇸🇷", "flag: Suriname", listOf("flag")),
    EmojiEntry("🇸🇸", "flag: South Sudan", listOf("flag")),
    EmojiEntry("🇸🇹", "flag: São Tomé & Príncipe", listOf("flag")),
    EmojiEntry("🇸🇻", "flag: El Salvador", listOf("flag")),
    EmojiEntry("🇸🇽", "flag: Sint Maarten", listOf("flag")),
    EmojiEntry("🇸🇾", "flag: Syria", listOf("flag")),
    EmojiEntry("🇸🇿", "flag: Eswatini", listOf("flag")),
    EmojiEntry("🇹🇦", "flag: Tristan da Cunha", listOf("flag")),
    EmojiEntry("🇹🇨", "flag: Turks & Caicos Islands", listOf("flag")),
    EmojiEntry("🇹🇩", "flag: Chad", listOf("flag")),
    EmojiEntry("🇹🇫", "flag: French Southern Territories", listOf("flag")),
    EmojiEntry("🇹🇬", "flag: Togo", listOf("flag")),
    EmojiEntry("🇹🇭", "flag: Thailand", listOf("flag")),
    EmojiEntry("🇹🇯", "flag: Tajikistan", listOf("flag")),
    EmojiEntry("🇹🇰", "flag: Tokelau", listOf("flag")),
    EmojiEntry("🇹🇱", "flag: Timor-Leste", listOf("flag")),
    EmojiEntry("🇹🇲", "flag: Turkmenistan", listOf("flag")),
    EmojiEntry("🇹🇳", "flag: Tunisia", listOf("flag")),
    EmojiEntry("🇹🇴", "flag: Tonga", listOf("flag")),
    EmojiEntry("🇹🇷", "flag: Turkey", listOf("flag")),
    EmojiEntry("🇹🇹", "flag: Trinidad & Tobago", listOf("flag")),
    EmojiEntry("🇹🇻", "flag: Tuvalu", listOf("flag")),
    EmojiEntry("🇹🇼", "flag: Taiwan", listOf("flag")),
    EmojiEntry("🇹🇿", "flag: Tanzania", listOf("flag")),
    EmojiEntry("🇺🇦", "flag: Ukraine", listOf("flag")),
    EmojiEntry("🇺🇬", "flag: Uganda", listOf("flag")),
    EmojiEntry("🇺🇲", "flag: U.S. Outlying Islands", listOf("flag")),
    EmojiEntry("🇺🇳", "flag: United Nations", listOf("flag")),
    EmojiEntry("🇺🇸", "flag: United States", listOf("flag")),
    EmojiEntry("🇺🇾", "flag: Uruguay", listOf("flag")),
    EmojiEntry("🇺🇿", "flag: Uzbekistan", listOf("flag")),
    EmojiEntry("🇻🇦", "flag: Vatican City", listOf("flag")),
    EmojiEntry("🇻🇨", "flag: St. Vincent & Grenadines", listOf("flag")),
)
