package com.zacksimpson.emojis

// Auto-generated from the RN app's utils/emojiData.ts via scripts/convert-emoji-index.js — do not hand-edit.
// Part 7/13 of EMOJI_INDEX, split across files so each file's <clinit> stays under the JVM's 64KB method size limit.
internal val EMOJI_INDEX_PART_6: List<EmojiEntry> = listOf(
    EmojiEntry("✈", "airplane", listOf("aeroplane", "airplane")),
    EmojiEntry("🛩", "small airplane", listOf("aeroplane", "airplane", "small airplane")),
    EmojiEntry("🛫", "airplane departure", listOf("aeroplane", "airplane", "check-in", "departure", "departures")),
    EmojiEntry("🛬", "airplane arrival", listOf("aeroplane", "airplane", "airplane arrival", "arrivals", "arriving", "landing")),
    EmojiEntry("🪂", "parachute", listOf("hang-glide", "parachute", "parasail", "skydive")),
    EmojiEntry("💺", "seat", listOf("chair", "seat")),
    EmojiEntry("🚁", "helicopter", listOf("helicopter", "vehicle")),
    EmojiEntry("🚟", "suspension railway", listOf("railway", "suspension")),
    EmojiEntry("🚠", "mountain cableway", listOf("cable", "gondola", "mountain", "mountain cableway")),
    EmojiEntry("🚡", "aerial tramway", listOf("aerial", "cable", "car", "gondola", "tramway")),
    EmojiEntry("🛰", "satellite", listOf("satellite", "space")),
    EmojiEntry("🚀", "rocket", listOf("rocket", "space")),
    EmojiEntry("🛸", "flying saucer", listOf("flying saucer", "UFO")),
    EmojiEntry("🛎", "bellhop bell", listOf("bell", "bellhop", "hotel")),
    EmojiEntry("🧳", "luggage", listOf("luggage", "packing", "travel")),
    EmojiEntry("⌛", "hourglass done", listOf("hourglass done", "sand", "timer")),
    EmojiEntry("⏳", "hourglass not done", listOf("hourglass", "hourglass not done", "sand", "timer")),
    EmojiEntry("⌚", "watch", listOf("clock", "watch")),
    EmojiEntry("⏰", "alarm clock", listOf("alarm", "clock")),
    EmojiEntry("⏱", "stopwatch", listOf("clock", "stopwatch")),
    EmojiEntry("⏲", "timer clock", listOf("clock", "timer")),
    EmojiEntry("🕰", "mantelpiece clock", listOf("clock", "mantelpiece clock")),
    EmojiEntry("🕛", "twelve oclock", listOf("00", "12", "12:00", "clock", "oclock", "twelve")),
    EmojiEntry("🕧", "twelve-thirty", listOf("12", "12:30", "clock", "thirty", "twelve", "twelve-thirty")),
    EmojiEntry("🕐", "one oclock", listOf("00", "1", "1:00", "clock", "oclock", "one")),
    EmojiEntry("🕜", "one-thirty", listOf("1", "1:30", "clock", "one", "one-thirty", "thirty")),
    EmojiEntry("🕑", "two oclock", listOf("00", "2", "2:00", "clock", "oclock", "two")),
    EmojiEntry("🕝", "two-thirty", listOf("2", "2:30", "clock", "thirty", "two", "two-thirty")),
    EmojiEntry("🕒", "three oclock", listOf("00", "3", "3:00", "clock", "oclock", "three")),
    EmojiEntry("🕞", "three-thirty", listOf("3", "3:30", "clock", "thirty", "three", "three-thirty")),
    EmojiEntry("🕓", "four oclock", listOf("00", "4", "4:00", "clock", "four", "oclock")),
    EmojiEntry("🕟", "four-thirty", listOf("4", "4:30", "clock", "four", "four-thirty", "thirty")),
    EmojiEntry("🕔", "five oclock", listOf("00", "5", "5:00", "clock", "five", "oclock")),
    EmojiEntry("🕠", "five-thirty", listOf("5", "5:30", "clock", "five", "five-thirty", "thirty")),
    EmojiEntry("🕕", "six oclock", listOf("00", "6", "6:00", "clock", "oclock", "six")),
    EmojiEntry("🕡", "six-thirty", listOf("6", "6:30", "clock", "six", "six-thirty", "thirty")),
    EmojiEntry("🕖", "seven oclock", listOf("00", "7", "7:00", "clock", "oclock", "seven")),
    EmojiEntry("🕢", "seven-thirty", listOf("7", "7:30", "clock", "seven", "seven-thirty", "thirty")),
    EmojiEntry("🕗", "eight oclock", listOf("00", "8", "8:00", "clock", "eight", "oclock")),
    EmojiEntry("🕣", "eight-thirty", listOf("8", "8:30", "clock", "eight", "eight-thirty", "thirty")),
    EmojiEntry("🕘", "nine oclock", listOf("00", "9", "9:00", "clock", "nine", "oclock")),
    EmojiEntry("🕤", "nine-thirty", listOf("9", "9:30", "clock", "nine", "nine-thirty", "thirty")),
    EmojiEntry("🕙", "ten oclock", listOf("00", "10", "10:00", "clock", "oclock", "ten")),
    EmojiEntry("🕥", "ten-thirty", listOf("10", "10:30", "clock", "ten", "ten-thirty", "thirty")),
    EmojiEntry("🕚", "eleven oclock", listOf("00", "11", "11:00", "clock", "eleven", "oclock")),
    EmojiEntry("🕦", "eleven-thirty", listOf("11", "11:30", "clock", "eleven", "eleven-thirty", "thirty")),
    EmojiEntry("🌑", "new moon", listOf("dark", "moon", "new moon")),
    EmojiEntry("🌒", "waxing crescent moon", listOf("crescent", "moon", "waxing")),
    EmojiEntry("🌓", "first quarter moon", listOf("first quarter moon", "moon", "quarter")),
    EmojiEntry("🌔", "waxing gibbous moon", listOf("gibbous", "moon", "waxing")),
    EmojiEntry("🌕", "full moon", listOf("full", "moon")),
    EmojiEntry("🌖", "waning gibbous moon", listOf("gibbous", "moon", "waning")),
    EmojiEntry("🌗", "last quarter moon", listOf("last quarter moon", "moon", "quarter")),
    EmojiEntry("🌘", "waning crescent moon", listOf("crescent", "moon", "waning")),
    EmojiEntry("🌙", "crescent moon", listOf("crescent", "moon")),
    EmojiEntry("🌚", "new moon face", listOf("face", "moon", "new moon face")),
    EmojiEntry("🌛", "first quarter moon face", listOf("face", "first quarter moon face", "moon", "quarter")),
    EmojiEntry("🌜", "last quarter moon face", listOf("face", "last quarter moon face", "moon", "quarter")),
    EmojiEntry("🌡", "thermometer", listOf("thermometer", "weather")),
    EmojiEntry("☀", "sun", listOf("bright", "rays", "sun", "sunny")),
    EmojiEntry("🌝", "full moon face", listOf("bright", "face", "full", "moon")),
    EmojiEntry("🌞", "sun with face", listOf("bright", "face", "sun", "sun with face")),
    EmojiEntry("🪐", "ringed planet", listOf("ringed planet", "saturn", "saturnine")),
    EmojiEntry("⭐", "star", listOf("star")),
    EmojiEntry("🌟", "glowing star", listOf("glittery", "glow", "glowing star", "shining", "sparkle", "star")),
    EmojiEntry("🌠", "shooting star", listOf("falling", "shooting", "star")),
    EmojiEntry("🌌", "milky way", listOf("milky way", "space")),
    EmojiEntry("☁", "cloud", listOf("cloud", "weather")),
    EmojiEntry("⛅", "sun behind cloud", listOf("cloud", "sun", "sun behind cloud")),
    EmojiEntry("⛈", "cloud with lightning and rain", listOf("cloud", "cloud with lightning and rain", "rain", "thunder")),
    EmojiEntry("🌤", "sun behind small cloud", listOf("cloud", "sun", "sun behind small cloud")),
    EmojiEntry("🌥", "sun behind large cloud", listOf("cloud", "sun", "sun behind large cloud")),
    EmojiEntry("🌦", "sun behind rain cloud", listOf("cloud", "rain", "sun", "sun behind rain cloud")),
    EmojiEntry("🌧", "cloud with rain", listOf("cloud", "cloud with rain", "rain")),
    EmojiEntry("🌨", "cloud with snow", listOf("cloud", "cloud with snow", "cold", "snow")),
    EmojiEntry("🌩", "cloud with lightning", listOf("cloud", "cloud with lightning", "lightning")),
    EmojiEntry("🌪", "tornado", listOf("cloud", "tornado", "whirlwind")),
    EmojiEntry("🌫", "fog", listOf("cloud", "fog")),
    EmojiEntry("🌬", "wind face", listOf("blow", "cloud", "face", "wind")),
    EmojiEntry("🌀", "cyclone", listOf("cyclone", "dizzy", "hurricane", "twister", "typhoon")),
    EmojiEntry("🌈", "rainbow", listOf("rain", "rainbow")),
    EmojiEntry("🌂", "closed umbrella", listOf("closed umbrella", "clothing", "rain", "umbrella")),
    EmojiEntry("☂", "umbrella", listOf("clothing", "rain", "umbrella")),
    EmojiEntry("☔", "umbrella with rain drops", listOf("clothing", "drop", "rain", "umbrella", "umbrella with rain drops")),
    EmojiEntry("⛱", "umbrella on ground", listOf("rain", "sun", "umbrella", "umbrella on ground")),
    EmojiEntry("⚡", "high voltage", listOf("danger", "electric", "high voltage", "lightning", "voltage", "zap")),
    EmojiEntry("❄", "snowflake", listOf("cold", "snow", "snowflake")),
    EmojiEntry("☃", "snowman", listOf("cold", "snow", "snowman")),
    EmojiEntry("⛄", "snowman without snow", listOf("cold", "snow", "snowman", "snowman without snow")),
    EmojiEntry("☄", "comet", listOf("comet", "space")),
    EmojiEntry("🔥", "fire", listOf("fire", "flame", "tool")),
    EmojiEntry("💧", "droplet", listOf("cold", "comic", "drop", "droplet", "sweat")),
    EmojiEntry("🌊", "water wave", listOf("ocean", "water", "wave")),
    EmojiEntry("🎃", "jack-o-lantern", listOf("celebration", "halloween", "jack", "jack-o-lantern", "lantern")),
    EmojiEntry("🎄", "Christmas tree", listOf("celebration", "Christmas", "tree")),
    EmojiEntry("🎆", "fireworks", listOf("celebration", "fireworks")),
    EmojiEntry("🎇", "sparkler", listOf("celebration", "fireworks", "sparkle", "sparkler")),
    EmojiEntry("🧨", "firecracker", listOf("dynamite", "explosive", "firecracker", "fireworks")),
    EmojiEntry("✨", "sparkles", listOf("*", "sparkle", "sparkles", "star")),
    EmojiEntry("🎈", "balloon", listOf("balloon", "celebration")),
    EmojiEntry("🎉", "party popper", listOf("celebration", "party", "popper", "tada")),
    EmojiEntry("🎊", "confetti ball", listOf("ball", "celebration", "confetti")),
    EmojiEntry("🎋", "tanabata tree", listOf("banner", "celebration", "Japanese", "tanabata tree", "tree")),
    EmojiEntry("🎍", "pine decoration", listOf("bamboo", "celebration", "Japanese", "pine", "pine decoration")),
    EmojiEntry("🎎", "Japanese dolls", listOf("celebration", "doll", "festival", "Japanese", "Japanese dolls")),
    EmojiEntry("🎏", "carp streamer", listOf("carp", "celebration", "streamer")),
    EmojiEntry("🎐", "wind chime", listOf("bell", "celebration", "chime", "wind")),
    EmojiEntry("🎑", "moon viewing ceremony", listOf("celebration", "ceremony", "moon", "moon viewing ceremony")),
    EmojiEntry("🧧", "red envelope", listOf("gift", "good luck", "hóngb?o", "lai see", "money", "red envelope")),
    EmojiEntry("🎀", "ribbon", listOf("celebration", "ribbon")),
    EmojiEntry("🎁", "wrapped gift", listOf("box", "celebration", "gift", "present", "wrapped")),
    EmojiEntry("🎗", "reminder ribbon", listOf("celebration", "reminder", "ribbon")),
    EmojiEntry("🎟", "admission tickets", listOf("admission", "admission tickets", "ticket")),
    EmojiEntry("🎫", "ticket", listOf("admission", "ticket")),
    EmojiEntry("🎖", "military medal", listOf("celebration", "medal", "military")),
    EmojiEntry("🏆", "trophy", listOf("prize", "trophy")),
    EmojiEntry("🏅", "sports medal", listOf("medal", "sports medal")),
    EmojiEntry("🥇", "1st place medal", listOf("1st place medal", "first", "gold", "medal")),
    EmojiEntry("🥈", "2nd place medal", listOf("2nd place medal", "medal", "second", "silver")),
    EmojiEntry("🥉", "3rd place medal", listOf("3rd place medal", "bronze", "medal", "third")),
    EmojiEntry("⚽", "soccer ball", listOf("ball", "football", "soccer")),
    EmojiEntry("⚾", "baseball", listOf("ball", "baseball")),
    EmojiEntry("🥎", "softball", listOf("ball", "glove", "softball", "underarm")),
    EmojiEntry("🏀", "basketball", listOf("ball", "basketball", "hoop")),
    EmojiEntry("🏐", "volleyball", listOf("ball", "game", "volleyball")),
    EmojiEntry("🏈", "american football", listOf("american", "ball", "football")),
    EmojiEntry("🏉", "rugby football", listOf("ball", "football", "rugby")),
    EmojiEntry("🎾", "tennis", listOf("ball", "racquet", "tennis")),
    EmojiEntry("🥏", "flying disc", listOf("flying disc", "ultimate")),
    EmojiEntry("🎳", "bowling", listOf("ball", "bowling", "game")),
    EmojiEntry("🏏", "cricket game", listOf("ball", "bat", "cricket game", "game")),
    EmojiEntry("🏑", "field hockey", listOf("ball", "field", "game", "hockey", "stick")),
    EmojiEntry("🏒", "ice hockey", listOf("game", "hockey", "ice", "puck", "stick")),
    EmojiEntry("🥍", "lacrosse", listOf("ball", "goal", "lacrosse", "stick")),
    EmojiEntry("🏓", "ping pong", listOf("ball", "bat", "game", "paddle", "ping pong", "table tennis")),
    EmojiEntry("🏸", "badminton", listOf("badminton", "birdie", "game", "racquet", "shuttlecock")),
    EmojiEntry("🥊", "boxing glove", listOf("boxing", "glove")),
    EmojiEntry("🥋", "martial arts uniform", listOf("judo", "karate", "martial arts", "martial arts uniform", "taekwondo", "uniform")),
    EmojiEntry("🥅", "goal net", listOf("goal", "net")),
    EmojiEntry("⛳", "flag in hole", listOf("flag in hole", "golf", "hole")),
    EmojiEntry("⛸", "ice skate", listOf("ice", "skate")),
    EmojiEntry("🎣", "fishing pole", listOf("fish", "fishing pole", "pole")),
    EmojiEntry("🤿", "diving mask", listOf("diving", "diving mask", "scuba", "snorkeling")),
    EmojiEntry("🎽", "running shirt", listOf("athletics", "running", "sash", "shirt")),
    EmojiEntry("🎿", "skis", listOf("ski", "skis", "snow")),
    EmojiEntry("🛷", "sled", listOf("sled", "sledge", "sleigh", "luge", "toboggan")),
    EmojiEntry("🥌", "curling stone", listOf("curling stone", "game", "rock")),
    EmojiEntry("🎯", "bullseye", listOf("bullseye", "dart", "direct hit", "game", "hit", "target")),
    EmojiEntry("🪀", "yo-yo", listOf("fluctuate", "toy", "yo-yo")),
    EmojiEntry("🪁", "kite", listOf("fly", "kite", "soar")),
)
