package com.zacksimpson.emojis

// Auto-generated from the RN app's utils/emojiData.ts via scripts/convert-emoji-index.js — do not hand-edit.
// Part 3/13 of EMOJI_INDEX, split across files so each file's <clinit> stays under the JVM's 64KB method size limit.
internal val EMOJI_INDEX_PART_2: List<EmojiEntry> = listOf(
    EmojiEntry("👩‍🎤", "woman singer", listOf("actor", "entertainer", "rock", "singer", "star", "woman")),
    EmojiEntry("🧑‍🎨", "artist", listOf("artist", "palette")),
    EmojiEntry("👨‍🎨", "man artist", listOf("artist", "man", "palette")),
    EmojiEntry("👩‍🎨", "woman artist", listOf("artist", "palette", "woman")),
    EmojiEntry("🧑‍✈️", "pilot", listOf("pilot", "plane")),
    EmojiEntry("👨‍✈️", "man pilot", listOf("man", "pilot", "plane")),
    EmojiEntry("👩‍✈️", "woman pilot", listOf("pilot", "plane", "woman")),
    EmojiEntry("🧑‍🚀", "astronaut", listOf("astronaut", "rocket")),
    EmojiEntry("👨‍🚀", "man astronaut", listOf("astronaut", "man", "rocket")),
    EmojiEntry("👩‍🚀", "woman astronaut", listOf("astronaut", "rocket", "woman")),
    EmojiEntry("🧑‍🚒", "firefighter", listOf("firefighter", "firetruck")),
    EmojiEntry("👨‍🚒", "man firefighter", listOf("firefighter", "firetruck", "man")),
    EmojiEntry("👩‍🚒", "woman firefighter", listOf("firefighter", "firetruck", "woman")),
    EmojiEntry("👮", "police officer", listOf("cop", "officer", "police")),
    EmojiEntry("👮‍♂️", "man police officer", listOf("cop", "man", "officer", "police")),
    EmojiEntry("👮‍♀️", "woman police officer", listOf("cop", "officer", "police", "woman")),
    EmojiEntry("🕵", "detective", listOf("detective", "sleuth", "spy")),
    EmojiEntry("🕵️‍♂️", "man detective", listOf("detective", "man", "sleuth", "spy")),
    EmojiEntry("🕵️‍♀️", "woman detective", listOf("detective", "sleuth", "spy", "woman")),
    EmojiEntry("💂", "guard", listOf("guard")),
    EmojiEntry("💂‍♂️", "man guard", listOf("guard", "man")),
    EmojiEntry("💂‍♀️", "woman guard", listOf("guard", "woman")),
    EmojiEntry("🥷", "ninja", listOf("fighter", "hidden", "ninja", "stealth")),
    EmojiEntry("👷", "construction worker", listOf("construction", "hat", "worker")),
    EmojiEntry("👷‍♂️", "man construction worker", listOf("construction", "man", "worker")),
    EmojiEntry("👷‍♀️", "woman construction worker", listOf("construction", "woman", "worker")),
    EmojiEntry("🤴", "prince", listOf("prince")),
    EmojiEntry("👸", "princess", listOf("fairy tale", "fantasy", "princess")),
    EmojiEntry("👳", "person wearing turban", listOf("person wearing turban", "turban")),
    EmojiEntry("👳‍♂️", "man wearing turban", listOf("man", "man wearing turban", "turban")),
    EmojiEntry("👳‍♀️", "woman wearing turban", listOf("turban", "woman", "woman wearing turban")),
    EmojiEntry("👲", "person with skullcap", listOf("cap", "gua pi mao", "hat", "person", "person with skullcap", "skullcap")),
    EmojiEntry("🧕", "woman with headscarf", listOf("headscarf", "hijab", "mantilla", "tichel", "woman with headscarf", "bandana", "head kerchief")),
    EmojiEntry("🤵", "person in tuxedo", listOf("groom", "person", "person in tuxedo", "tuxedo")),
    EmojiEntry("🤵‍♂️", "man in tuxedo", listOf("man", "man in tuxedo", "tuxedo")),
    EmojiEntry("🤵‍♀️", "woman in tuxedo", listOf("tuxedo", "woman", "woman in tuxedo")),
    EmojiEntry("👰", "person with veil", listOf("bride", "person", "person with veil", "veil", "wedding")),
    EmojiEntry("👰‍♂️", "man with veil", listOf("man", "man with veil", "veil")),
    EmojiEntry("👰‍♀️", "woman with veil", listOf("veil", "woman", "woman with veil")),
    EmojiEntry("🤰", "pregnant woman", listOf("pregnant", "woman")),
    EmojiEntry("🤱", "breast-feeding", listOf("baby", "breast", "breast-feeding", "nursing")),
    EmojiEntry("👩‍🍼", "woman feeding baby", listOf("baby", "feeding", "nursing", "woman")),
    EmojiEntry("👨‍🍼", "man feeding baby", listOf("baby", "feeding", "man", "nursing")),
    EmojiEntry("🧑‍🍼", "person feeding baby", listOf("baby", "feeding", "nursing", "person")),
    EmojiEntry("👼", "baby angel", listOf("angel", "baby", "face", "fairy tale", "fantasy")),
    EmojiEntry("🎅", "Santa Claus", listOf("celebration", "Christmas", "claus", "father", "santa", "Santa Claus")),
    EmojiEntry("🤶", "Mrs. Claus", listOf("celebration", "Christmas", "claus", "mother", "Mrs.", "Mrs. Claus")),
    EmojiEntry("🧑‍🎄", "mx claus", listOf("Claus, christmas", "mx claus")),
    EmojiEntry("🦸", "superhero", listOf("good", "hero", "heroine", "superhero", "superpower")),
    EmojiEntry("🦸‍♂️", "man superhero", listOf("good", "hero", "man", "man superhero", "superpower")),
    EmojiEntry("🦸‍♀️", "woman superhero", listOf("good", "hero", "heroine", "superpower", "woman", "woman superhero")),
    EmojiEntry("🦹", "supervillain", listOf("criminal", "evil", "superpower", "supervillain", "villain")),
    EmojiEntry("🦹‍♂️", "man supervillain", listOf("criminal", "evil", "man", "man supervillain", "superpower", "villain")),
    EmojiEntry("🦹‍♀️", "woman supervillain", listOf("criminal", "evil", "superpower", "villain", "woman", "woman supervillain")),
    EmojiEntry("🧙", "mage", listOf("mage", "sorcerer", "sorceress", "witch", "wizard")),
    EmojiEntry("🧙‍♂️", "man mage", listOf("man mage", "sorcerer", "wizard")),
    EmojiEntry("🧙‍♀️", "woman mage", listOf("sorceress", "witch", "woman mage")),
    EmojiEntry("🧚", "fairy", listOf("fairy", "Oberon", "Puck", "Titania")),
    EmojiEntry("🧚‍♂️", "man fairy", listOf("man fairy", "Oberon", "Puck")),
    EmojiEntry("🧚‍♀️", "woman fairy", listOf("Titania", "woman fairy")),
    EmojiEntry("🧛", "vampire", listOf("Dracula", "undead", "vampire")),
    EmojiEntry("🧛‍♂️", "man vampire", listOf("Dracula", "man vampire", "undead")),
    EmojiEntry("🧛‍♀️", "woman vampire", listOf("undead", "woman vampire")),
    EmojiEntry("🧜", "merperson", listOf("mermaid", "merman", "merperson", "merwoman")),
    EmojiEntry("🧜‍♂️", "merman", listOf("merman", "Triton")),
    EmojiEntry("🧜‍♀️", "mermaid", listOf("mermaid", "merwoman")),
    EmojiEntry("🧝", "elf", listOf("elf", "magical", "LOTR style")),
    EmojiEntry("🧝‍♂️", "man elf", listOf("magical", "man elf")),
    EmojiEntry("🧝‍♀️", "woman elf", listOf("magical", "woman elf")),
    EmojiEntry("🧞", "genie", listOf("djinn", "genie", "(non-human color)")),
    EmojiEntry("🧞‍♂️", "man genie", listOf("djinn", "man genie")),
    EmojiEntry("🧞‍♀️", "woman genie", listOf("djinn", "woman genie")),
    EmojiEntry("🧟", "zombie", listOf("undead", "walking dead", "zombie", "(non-human color)")),
    EmojiEntry("🧟‍♂️", "man zombie", listOf("man zombie", "undead", "walking dead")),
    EmojiEntry("🧟‍♀️", "woman zombie", listOf("undead", "walking dead", "woman zombie")),
    EmojiEntry("💆", "person getting massage", listOf("face", "massage", "person getting massage", "salon")),
    EmojiEntry("💆‍♂️", "man getting massage", listOf("face", "man", "man getting massage", "massage")),
    EmojiEntry("💆‍♀️", "woman getting massage", listOf("face", "massage", "woman", "woman getting massage")),
    EmojiEntry("💇", "person getting haircut", listOf("barber", "beauty", "haircut", "parlor", "person getting haircut")),
    EmojiEntry("💇‍♂️", "man getting haircut", listOf("haircut", "man", "man getting haircut")),
    EmojiEntry("💇‍♀️", "woman getting haircut", listOf("haircut", "woman", "woman getting haircut")),
    EmojiEntry("🚶", "person walking", listOf("hike", "person walking", "walk", "walking")),
    EmojiEntry("🚶‍♂️", "man walking", listOf("hike", "man", "man walking", "walk")),
    EmojiEntry("🚶‍♀️", "woman walking", listOf("hike", "walk", "woman", "woman walking")),
    EmojiEntry("🧍", "person standing", listOf("person standing", "stand", "standing")),
    EmojiEntry("🧍‍♂️", "man standing", listOf("man", "standing")),
    EmojiEntry("🧍‍♀️", "woman standing", listOf("standing", "woman")),
    EmojiEntry("🧎", "person kneeling", listOf("kneel", "kneeling", "person kneeling")),
    EmojiEntry("🧎‍♂️", "man kneeling", listOf("kneeling", "man")),
    EmojiEntry("🧎‍♀️", "woman kneeling", listOf("kneeling", "woman")),
    EmojiEntry("🧑‍🦯", "person with white cane", listOf("accessibility", "blind", "person with white cane")),
    EmojiEntry("👨‍🦯", "man with white cane", listOf("accessibility", "blind", "man", "man with white cane")),
    EmojiEntry("👩‍🦯", "woman with white cane", listOf("accessibility", "blind", "woman", "woman with white cane")),
    EmojiEntry("🧑‍🦼", "person in motorized wheelchair", listOf("accessibility", "person in motorized wheelchair", "wheelchair")),
    EmojiEntry("👨‍🦼", "man in motorized wheelchair", listOf("accessibility", "man", "man in motorized wheelchair", "wheelchair")),
    EmojiEntry("👩‍🦼", "woman in motorized wheelchair", listOf("accessibility", "wheelchair", "woman", "woman in motorized wheelchair")),
    EmojiEntry("🧑‍🦽", "person in manual wheelchair", listOf("accessibility", "person in manual wheelchair", "wheelchair")),
    EmojiEntry("👨‍🦽", "man in manual wheelchair", listOf("accessibility", "man", "man in manual wheelchair", "wheelchair")),
    EmojiEntry("👩‍🦽", "woman in manual wheelchair", listOf("accessibility", "wheelchair", "woman", "woman in manual wheelchair")),
    EmojiEntry("🏃", "person running", listOf("marathon", "person running", "running")),
    EmojiEntry("🏃‍♂️", "man running", listOf("man", "marathon", "racing", "running")),
    EmojiEntry("🏃‍♀️", "woman running", listOf("marathon", "racing", "running", "woman")),
    EmojiEntry("💃", "woman dancing", listOf("dance", "dancing", "woman")),
    EmojiEntry("🕺", "man dancing", listOf("dance", "dancing", "man")),
    EmojiEntry("🕴", "person in suit levitating", listOf("business", "person", "person in suit levitating", "suit")),
    EmojiEntry("👯", "people with bunny ears", listOf("bunny ear", "dancer", "partying", "people with bunny ears")),
    EmojiEntry("👯‍♂️", "men with bunny ears", listOf("bunny ear", "dancer", "men", "men with bunny ears", "partying")),
    EmojiEntry("👯‍♀️", "women with bunny ears", listOf("bunny ear", "dancer", "partying", "women", "women with bunny ears")),
    EmojiEntry("🧖", "person in steamy room", listOf("person in steamy room", "sauna", "steam room", "hamam", "steambath")),
    EmojiEntry("🧖‍♂️", "man in steamy room", listOf("man in steamy room", "sauna", "steam room")),
    EmojiEntry("🧖‍♀️", "woman in steamy room", listOf("sauna", "steam room", "woman in steamy room")),
    EmojiEntry("🧗", "person climbing", listOf("climber", "person climbing")),
    EmojiEntry("🧗‍♂️", "man climbing", listOf("climber", "man climbing")),
    EmojiEntry("🧗‍♀️", "woman climbing", listOf("climber", "woman climbing")),
    EmojiEntry("🤺", "person fencing", listOf("fencer", "fencing", "person fencing", "sword")),
    EmojiEntry("🏇", "horse racing", listOf("horse", "jockey", "racehorse", "racing")),
    EmojiEntry("⛷", "skier", listOf("ski", "skier", "snow")),
    EmojiEntry("🏂", "snowboarder", listOf("ski", "snow", "snowboard", "snowboarder")),
    EmojiEntry("🏌", "person golfing", listOf("ball", "golf", "person golfing")),
    EmojiEntry("🏌️‍♂️", "man golfing", listOf("golf", "man", "man golfing")),
    EmojiEntry("🏌️‍♀️", "woman golfing", listOf("golf", "woman", "woman golfing")),
    EmojiEntry("🏄", "person surfing", listOf("person surfing", "surfing")),
    EmojiEntry("🏄‍♂️", "man surfing", listOf("man", "surfing")),
    EmojiEntry("🏄‍♀️", "woman surfing", listOf("surfing", "woman")),
    EmojiEntry("🚣", "person rowing boat", listOf("boat", "person rowing boat", "rowboat")),
    EmojiEntry("🚣‍♂️", "man rowing boat", listOf("boat", "man", "man rowing boat", "rowboat")),
    EmojiEntry("🚣‍♀️", "woman rowing boat", listOf("boat", "rowboat", "woman", "woman rowing boat")),
    EmojiEntry("🏊", "person swimming", listOf("person swimming", "swim")),
    EmojiEntry("🏊‍♂️", "man swimming", listOf("man", "man swimming", "swim")),
    EmojiEntry("🏊‍♀️", "woman swimming", listOf("swim", "woman", "woman swimming")),
    EmojiEntry("⛹", "person bouncing ball", listOf("ball", "person bouncing ball")),
    EmojiEntry("⛹️‍♂️", "man bouncing ball", listOf("ball", "man", "man bouncing ball")),
    EmojiEntry("⛹️‍♀️", "woman bouncing ball", listOf("ball", "woman", "woman bouncing ball")),
    EmojiEntry("🏋", "person lifting weights", listOf("lifter", "person lifting weights", "weight")),
    EmojiEntry("🏋️‍♂️", "man lifting weights", listOf("man", "man lifting weights", "weight lifter")),
    EmojiEntry("🏋️‍♀️", "woman lifting weights", listOf("weight lifter", "woman", "woman lifting weights")),
    EmojiEntry("🚴", "person biking", listOf("bicycle", "biking", "cyclist", "person biking")),
    EmojiEntry("🚴‍♂️", "man biking", listOf("bicycle", "biking", "cyclist", "man")),
    EmojiEntry("🚴‍♀️", "woman biking", listOf("bicycle", "biking", "cyclist", "woman")),
    EmojiEntry("🚵", "person mountain biking", listOf("bicycle", "bicyclist", "bike", "cyclist", "mountain", "person mountain biking")),
    EmojiEntry("🚵‍♂️", "man mountain biking", listOf("bicycle", "bike", "cyclist", "man", "man mountain biking", "mountain")),
    EmojiEntry("🚵‍♀️", "woman mountain biking", listOf("bicycle", "bike", "biking", "cyclist", "mountain", "woman")),
    EmojiEntry("🤸", "person cartwheeling", listOf("cartwheel", "gymnastics", "person cartwheeling")),
    EmojiEntry("🤸‍♂️", "man cartwheeling", listOf("cartwheel", "gymnastics", "man", "man cartwheeling")),
    EmojiEntry("🤸‍♀️", "woman cartwheeling", listOf("cartwheel", "gymnastics", "woman", "woman cartwheeling")),
    EmojiEntry("🤼", "people wrestling", listOf("people wrestling", "wrestle", "wrestler")),
    EmojiEntry("🤼‍♂️", "men wrestling", listOf("men", "men wrestling", "wrestle")),
    EmojiEntry("🤼‍♀️", "women wrestling", listOf("women", "women wrestling", "wrestle")),
    EmojiEntry("🤽", "person playing water polo", listOf("person playing water polo", "polo", "water")),
    EmojiEntry("🤽‍♂️", "man playing water polo", listOf("man", "man playing water polo", "water polo")),
)
