package com.zacksimpson.emojis

// Auto-generated from the RN app's utils/emojiData.ts via scripts/convert-emoji-index.js — do not hand-edit.
// Part 6/13 of EMOJI_INDEX, split across files so each file's <clinit> stays under the JVM's 64KB method size limit.
internal val EMOJI_INDEX_PART_5: List<EmojiEntry> = listOf(
    EmojiEntry("🍭", "lollipop", listOf("candy", "dessert", "lollipop", "sweet")),
    EmojiEntry("🍮", "custard", listOf("custard", "dessert", "pudding", "sweet")),
    EmojiEntry("🍯", "honey pot", listOf("honey", "honeypot", "pot", "sweet")),
    EmojiEntry("🍼", "baby bottle", listOf("baby", "bottle", "drink", "milk")),
    EmojiEntry("🥛", "glass of milk", listOf("drink", "glass", "glass of milk", "milk")),
    EmojiEntry("☕", "hot beverage", listOf("beverage", "coffee", "drink", "hot", "steaming", "tea")),
    EmojiEntry("🫖", "teapot", listOf("drink", "pot", "tea", "teapot")),
    EmojiEntry("🍵", "teacup without handle", listOf("beverage", "cup", "drink", "tea", "teacup", "teacup without handle")),
    EmojiEntry("🍶", "sake", listOf("bar", "beverage", "bottle", "cup", "drink", "sake")),
    EmojiEntry("🍾", "bottle with popping cork", listOf("bar", "bottle", "bottle with popping cork", "cork", "drink", "popping")),
    EmojiEntry("🍷", "wine glass", listOf("bar", "beverage", "drink", "glass", "wine")),
    EmojiEntry("🍸", "cocktail glass", listOf("bar", "cocktail", "drink", "glass")),
    EmojiEntry("🍹", "tropical drink", listOf("bar", "drink", "tropical")),
    EmojiEntry("🍺", "beer mug", listOf("bar", "beer", "drink", "mug")),
    EmojiEntry("🍻", "clinking beer mugs", listOf("bar", "beer", "clink", "clinking beer mugs", "drink", "mug")),
    EmojiEntry("🥂", "clinking glasses", listOf("celebrate", "clink", "clinking glasses", "drink", "glass")),
    EmojiEntry("🥃", "tumbler glass", listOf("glass", "liquor", "shot", "tumbler", "whisky")),
    EmojiEntry("🥤", "cup with straw", listOf("cup with straw", "juice", "soda", "malt", "soft drink", "water")),
    EmojiEntry("🧋", "bubble tea", listOf("bubble", "milk", "pearl", "tea")),
    EmojiEntry("🧃", "beverage box", listOf("beverage", "box", "juice", "straw", "sweet")),
    EmojiEntry("🧉", "mate", listOf("drink", "mate")),
    EmojiEntry("🧊", "ice", listOf("cold", "ice", "ice cube", "iceberg")),
    EmojiEntry("🥢", "chopsticks", listOf("chopsticks", "hashi", "jeotgarak", "kuaizi")),
    EmojiEntry("🍽", "fork and knife with plate", listOf("cooking", "fork", "fork and knife with plate", "knife", "plate")),
    EmojiEntry("🍴", "fork and knife", listOf("cooking", "cutlery", "fork", "fork and knife", "knife")),
    EmojiEntry("🥄", "spoon", listOf("spoon", "tableware")),
    EmojiEntry("🔪", "kitchen knife", listOf("cooking", "hocho", "kitchen knife", "knife", "tool", "weapon")),
    EmojiEntry("🏺", "amphora", listOf("amphora", "Aquarius", "cooking", "drink", "jug", "zodiac")),
    EmojiEntry("🌍", "globe showing Europe-Africa", listOf("Africa", "earth", "Europe", "globe", "globe showing Europe-Africa", "world")),
    EmojiEntry("🌎", "globe showing Americas", listOf("Americas", "earth", "globe", "globe showing Americas", "world")),
    EmojiEntry("🌏", "globe showing Asia-Australia", listOf("Asia", "Australia", "earth", "globe", "globe showing Asia-Australia", "world")),
    EmojiEntry("🌐", "globe with meridians", listOf("earth", "globe", "globe with meridians", "meridians", "world")),
    EmojiEntry("🗺", "world map", listOf("map", "world")),
    EmojiEntry("🗾", "map of Japan", listOf("Japan", "map", "map of Japan")),
    EmojiEntry("🧭", "compass", listOf("compass", "magnetic", "navigation", "orienteering")),
    EmojiEntry("🏔", "snow-capped mountain", listOf("cold", "mountain", "snow", "snow-capped mountain")),
    EmojiEntry("⛰", "mountain", listOf("mountain")),
    EmojiEntry("🌋", "volcano", listOf("eruption", "mountain", "volcano")),
    EmojiEntry("🗻", "mount fuji", listOf("fuji", "mount fuji", "mountain")),
    EmojiEntry("🏕", "camping", listOf("camping")),
    EmojiEntry("🏖", "beach with umbrella", listOf("beach", "beach with umbrella", "umbrella")),
    EmojiEntry("🏜", "desert", listOf("desert")),
    EmojiEntry("🏝", "desert island", listOf("desert", "island")),
    EmojiEntry("🏞", "national park", listOf("national park", "park")),
    EmojiEntry("🏟", "stadium", listOf("stadium")),
    EmojiEntry("🏛", "classical building", listOf("classical", "classical building")),
    EmojiEntry("🏗", "building construction", listOf("building construction", "construction")),
    EmojiEntry("🧱", "brick", listOf("brick", "bricks", "clay", "mortar", "wall")),
    EmojiEntry("🪨", "rock", listOf("boulder", "heavy", "rock", "solid", "stone")),
    EmojiEntry("🪵", "wood", listOf("log", "lumber", "timber", "wood")),
    EmojiEntry("🛖", "hut", listOf("house", "hut", "roundhouse", "yurt")),
    EmojiEntry("🏘", "houses", listOf("houses")),
    EmojiEntry("🏚", "derelict house", listOf("derelict", "house")),
    EmojiEntry("🏠", "house", listOf("home", "house")),
    EmojiEntry("🏡", "house with garden", listOf("garden", "home", "house", "house with garden")),
    EmojiEntry("🏢", "office building", listOf("building", "office building")),
    EmojiEntry("🏣", "Japanese post office", listOf("Japanese", "Japanese post office", "post")),
    EmojiEntry("🏤", "post office", listOf("European", "post", "post office")),
    EmojiEntry("🏥", "hospital", listOf("doctor", "hospital", "medicine")),
    EmojiEntry("🏦", "bank", listOf("bank", "building")),
    EmojiEntry("🏨", "hotel", listOf("building", "hotel")),
    EmojiEntry("🏩", "love hotel", listOf("hotel", "love")),
    EmojiEntry("🏪", "convenience store", listOf("convenience", "store")),
    EmojiEntry("🏫", "school", listOf("building", "school")),
    EmojiEntry("🏬", "department store", listOf("department", "store")),
    EmojiEntry("🏭", "factory", listOf("building", "factory")),
    EmojiEntry("🏯", "Japanese castle", listOf("castle", "Japanese")),
    EmojiEntry("🏰", "castle", listOf("castle", "European")),
    EmojiEntry("💒", "wedding", listOf("chapel", "romance", "wedding")),
    EmojiEntry("🗼", "Tokyo tower", listOf("Tokyo", "tower")),
    EmojiEntry("🗽", "Statue of Liberty", listOf("liberty", "statue", "Statue of Liberty")),
    EmojiEntry("⛪", "church", listOf("Christian", "church", "cross", "religion")),
    EmojiEntry("🕌", "mosque", listOf("islam", "mosque", "Muslim", "religion")),
    EmojiEntry("🛕", "hindu temple", listOf("hindu", "temple")),
    EmojiEntry("🕍", "synagogue", listOf("Jew", "Jewish", "religion", "synagogue", "temple")),
    EmojiEntry("⛩", "shinto shrine", listOf("religion", "shinto", "shrine")),
    EmojiEntry("🕋", "kaaba", listOf("islam", "kaaba", "Muslim", "religion")),
    EmojiEntry("⛲", "fountain", listOf("fountain")),
    EmojiEntry("⛺", "tent", listOf("camping", "tent")),
    EmojiEntry("🌁", "foggy", listOf("fog", "foggy")),
    EmojiEntry("🌃", "night with stars", listOf("night", "night with stars", "star")),
    EmojiEntry("🏙", "cityscape", listOf("city", "cityscape")),
    EmojiEntry("🌄", "sunrise over mountains", listOf("morning", "mountain", "sun", "sunrise", "sunrise over mountains")),
    EmojiEntry("🌅", "sunrise", listOf("morning", "sun", "sunrise")),
    EmojiEntry("🌆", "cityscape at dusk", listOf("city", "cityscape at dusk", "dusk", "evening", "landscape", "sunset")),
    EmojiEntry("🌇", "sunset", listOf("dusk", "sun", "sunset")),
    EmojiEntry("🌉", "bridge at night", listOf("bridge", "bridge at night", "night")),
    EmojiEntry("♨", "hot springs", listOf("hot", "hotsprings", "springs", "steaming")),
    EmojiEntry("🎠", "carousel horse", listOf("carousel", "horse")),
    EmojiEntry("🎡", "ferris wheel", listOf("amusement park", "ferris", "wheel")),
    EmojiEntry("🎢", "roller coaster", listOf("amusement park", "coaster", "roller")),
    EmojiEntry("💈", "barber pole", listOf("barber", "haircut", "pole")),
    EmojiEntry("🎪", "circus tent", listOf("circus", "tent")),
    EmojiEntry("🚂", "locomotive", listOf("engine", "locomotive", "railway", "steam", "train")),
    EmojiEntry("🚃", "railway car", listOf("car", "electric", "railway", "train", "tram", "trolleybus")),
    EmojiEntry("🚄", "high-speed train", listOf("high-speed train", "railway", "shinkansen", "speed", "train")),
    EmojiEntry("🚅", "bullet train", listOf("bullet", "railway", "shinkansen", "speed", "train")),
    EmojiEntry("🚆", "train", listOf("railway", "train")),
    EmojiEntry("🚇", "metro", listOf("metro", "subway")),
    EmojiEntry("🚈", "light rail", listOf("light rail", "railway")),
    EmojiEntry("🚉", "station", listOf("railway", "station", "train")),
    EmojiEntry("🚊", "tram", listOf("tram", "trolleybus")),
    EmojiEntry("🚝", "monorail", listOf("monorail", "vehicle")),
    EmojiEntry("🚞", "mountain railway", listOf("car", "mountain", "railway")),
    EmojiEntry("🚋", "tram car", listOf("car", "tram", "trolleybus")),
    EmojiEntry("🚌", "bus", listOf("bus", "vehicle")),
    EmojiEntry("🚍", "oncoming bus", listOf("bus", "oncoming")),
    EmojiEntry("🚎", "trolleybus", listOf("bus", "tram", "trolley", "trolleybus")),
    EmojiEntry("🚐", "minibus", listOf("bus", "minibus")),
    EmojiEntry("🚑", "ambulance", listOf("ambulance", "vehicle")),
    EmojiEntry("🚒", "fire engine", listOf("engine", "fire", "truck")),
    EmojiEntry("🚓", "police car", listOf("car", "patrol", "police")),
    EmojiEntry("🚔", "oncoming police car", listOf("car", "oncoming", "police")),
    EmojiEntry("🚕", "taxi", listOf("taxi", "vehicle")),
    EmojiEntry("🚖", "oncoming taxi", listOf("oncoming", "taxi")),
    EmojiEntry("🚗", "automobile", listOf("automobile", "car")),
    EmojiEntry("🚘", "oncoming automobile", listOf("automobile", "car", "oncoming")),
    EmojiEntry("🚙", "sport utility vehicle", listOf("recreational", "sport utility", "sport utility vehicle")),
    EmojiEntry("🛻", "pickup truck", listOf("pick-up", "pickup", "truck")),
    EmojiEntry("🚚", "delivery truck", listOf("delivery", "truck")),
    EmojiEntry("🚛", "articulated lorry", listOf("articulated lorry", "lorry", "semi", "truck")),
    EmojiEntry("🚜", "tractor", listOf("tractor", "vehicle")),
    EmojiEntry("🏎", "racing car", listOf("car", "racing")),
    EmojiEntry("🏍", "motorcycle", listOf("motorcycle", "racing")),
    EmojiEntry("🛵", "motor scooter", listOf("motor", "scooter")),
    EmojiEntry("🦽", "manual wheelchair", listOf("accessibility", "manual wheelchair")),
    EmojiEntry("🦼", "motorized wheelchair", listOf("accessibility", "motorized wheelchair")),
    EmojiEntry("🛺", "auto rickshaw", listOf("auto rickshaw", "tuk tuk")),
    EmojiEntry("🚲", "bicycle", listOf("bicycle", "bike")),
    EmojiEntry("🛴", "kick scooter", listOf("kick", "scooter")),
    EmojiEntry("🛹", "skateboard", listOf("board", "skateboard")),
    EmojiEntry("🛼", "roller skate", listOf("roller", "skate")),
    EmojiEntry("🚏", "bus stop", listOf("bus", "busstop", "stop")),
    EmojiEntry("🛣", "motorway", listOf("highway", "motorway", "road")),
    EmojiEntry("🛤", "railway track", listOf("railway", "railway track", "train")),
    EmojiEntry("🛢", "oil drum", listOf("drum", "oil")),
    EmojiEntry("⛽", "fuel pump", listOf("diesel", "fuel", "fuelpump", "gas", "pump", "station")),
    EmojiEntry("🚨", "police car light", listOf("beacon", "car", "light", "police", "revolving")),
    EmojiEntry("🚥", "horizontal traffic light", listOf("horizontal traffic light", "light", "signal", "traffic")),
    EmojiEntry("🚦", "vertical traffic light", listOf("light", "signal", "traffic", "vertical traffic light")),
    EmojiEntry("🛑", "stop sign", listOf("octagonal", "sign", "stop")),
    EmojiEntry("🚧", "construction", listOf("barrier", "construction")),
    EmojiEntry("⚓", "anchor", listOf("anchor", "ship", "tool")),
    EmojiEntry("⛵", "sailboat", listOf("boat", "resort", "sailboat", "sea", "yacht")),
    EmojiEntry("🛶", "canoe", listOf("boat", "canoe")),
    EmojiEntry("🚤", "speedboat", listOf("boat", "speedboat")),
    EmojiEntry("🛳", "passenger ship", listOf("passenger", "ship")),
    EmojiEntry("⛴", "ferry", listOf("boat", "ferry", "passenger")),
    EmojiEntry("🛥", "motor boat", listOf("boat", "motor boat", "motorboat")),
    EmojiEntry("🚢", "ship", listOf("boat", "passenger", "ship")),
)
