package com.zacksimpson.emojis

// Auto-generated from the RN app's utils/emojiData.ts via scripts/convert-emoji-index.js — do not hand-edit.
// Part 8/13 of EMOJI_INDEX, split across files so each file's <clinit> stays under the JVM's 64KB method size limit.
internal val EMOJI_INDEX_PART_7: List<EmojiEntry> = listOf(
    EmojiEntry("🎱", "pool 8 ball", listOf("8", "ball", "billiard", "eight", "game", "pool 8 ball")),
    EmojiEntry("🔮", "crystal ball", listOf("ball", "crystal", "fairy tale", "fantasy", "fortune", "tool")),
    EmojiEntry("🪄", "magic wand", listOf("magic", "magic wand", "witch", "wizard")),
    EmojiEntry("🧿", "nazar amulet", listOf("bead", "charm", "evil-eye", "nazar", "nazar amulet", "talisman")),
    EmojiEntry("🎮", "video game", listOf("controller", "game", "video game")),
    EmojiEntry("🕹", "joystick", listOf("game", "joystick", "video game")),
    EmojiEntry("🎰", "slot machine", listOf("game", "slot", "slot machine")),
    EmojiEntry("🎲", "game die", listOf("dice", "die", "game")),
    EmojiEntry("🧩", "puzzle piece", listOf("clue", "interlocking", "jigsaw", "piece", "puzzle")),
    EmojiEntry("🧸", "teddy bear", listOf("plaything", "plush", "stuffed", "teddy bear", "toy")),
    EmojiEntry("🪅", "piñata", listOf("celebration", "party", "piñata")),
    EmojiEntry("🪆", "nesting dolls", listOf("doll", "nesting", "nesting dolls", "russia")),
    EmojiEntry("♠", "spade suit", listOf("card", "game", "spade suit")),
    EmojiEntry("♥", "heart suit", listOf("card", "game", "heart suit")),
    EmojiEntry("♦", "diamond suit", listOf("card", "diamond suit", "game")),
    EmojiEntry("♣", "club suit", listOf("card", "club suit", "game")),
    EmojiEntry("♟", "chess pawn", listOf("chess", "chess pawn", "dupe", "expendable")),
    EmojiEntry("🃏", "joker", listOf("card", "game", "joker", "wildcard")),
    EmojiEntry("🀄", "mahjong red dragon", listOf("game", "mahjong", "mahjong red dragon", "red")),
    EmojiEntry("🎴", "flower playing cards", listOf("card", "flower", "flower playing cards", "game", "Japanese", "playing")),
    EmojiEntry("🎭", "performing arts", listOf("art", "mask", "performing", "performing arts", "theater", "theatre")),
    EmojiEntry("🖼", "framed picture", listOf("art", "frame", "framed picture", "museum", "painting", "picture")),
    EmojiEntry("🎨", "artist palette", listOf("art", "artist palette", "museum", "painting", "palette")),
    EmojiEntry("🧵", "thread", listOf("needle", "sewing", "spool", "string", "thread")),
    EmojiEntry("🪡", "sewing needle", listOf("embroidery", "needle", "sewing", "stitches", "sutures", "tailoring")),
    EmojiEntry("🧶", "yarn", listOf("ball", "crochet", "knit", "yarn")),
    EmojiEntry("🪢", "knot", listOf("knot", "rope", "tangled", "tie", "twine", "twist")),
    EmojiEntry("👓", "glasses", listOf("clothing", "eye", "eyeglasses", "eyewear", "glasses")),
    EmojiEntry("🕶", "sunglasses", listOf("dark", "eye", "eyewear", "glasses", "sunglasses")),
    EmojiEntry("🥽", "goggles", listOf("eye protection", "goggles", "swimming", "welding")),
    EmojiEntry("🥼", "lab coat", listOf("doctor", "experiment", "lab coat", "scientist")),
    EmojiEntry("🦺", "safety vest", listOf("emergency", "safety", "vest")),
    EmojiEntry("👔", "necktie", listOf("clothing", "necktie", "tie")),
    EmojiEntry("👕", "t-shirt", listOf("clothing", "shirt", "t-shirt", "tshirt")),
    EmojiEntry("👖", "jeans", listOf("clothing", "jeans", "pants", "trousers")),
    EmojiEntry("🧣", "scarf", listOf("neck", "scarf")),
    EmojiEntry("🧤", "gloves", listOf("gloves", "hand")),
    EmojiEntry("🧥", "coat", listOf("coat", "jacket")),
    EmojiEntry("🧦", "socks", listOf("socks", "stocking")),
    EmojiEntry("👗", "dress", listOf("clothing", "dress")),
    EmojiEntry("👘", "kimono", listOf("clothing", "kimono")),
    EmojiEntry("🥻", "sari", listOf("clothing", "dress", "sari")),
    EmojiEntry("🩱", "one-piece swimsuit", listOf("bathing suit", "one-piece swimsuit")),
    EmojiEntry("🩲", "briefs", listOf("bathing suit", "briefs", "one-piece", "swimsuit", "underwear")),
    EmojiEntry("🩳", "shorts", listOf("bathing suit", "pants", "shorts", "underwear")),
    EmojiEntry("👙", "bikini", listOf("bikini", "clothing", "swim")),
    EmojiEntry("👚", "womans clothes", listOf("clothing", "woman", "womans clothes")),
    EmojiEntry("👛", "purse", listOf("clothing", "coin", "purse")),
    EmojiEntry("👜", "handbag", listOf("bag", "clothing", "handbag", "purse")),
    EmojiEntry("👝", "clutch bag", listOf("bag", "clothing", "clutch bag", "pouch")),
    EmojiEntry("🛍", "shopping bags", listOf("bag", "hotel", "shopping", "shopping bags")),
    EmojiEntry("🎒", "backpack", listOf("backpack", "bag", "rucksack", "satchel", "school")),
    EmojiEntry("🩴", "thong sandal", listOf("beach sandals", "sandals", "thong sandal", "thong sandals", "thongs", "z?ri")),
    EmojiEntry("👞", "mans shoe", listOf("clothing", "man", "mans shoe", "shoe")),
    EmojiEntry("👟", "running shoe", listOf("athletic", "clothing", "running shoe", "shoe", "sneaker")),
    EmojiEntry("🥾", "hiking boot", listOf("backpacking", "boot", "camping", "hiking")),
    EmojiEntry("🥿", "flat shoe", listOf("ballet flat", "flat shoe", "slip-on", "slipper")),
    EmojiEntry("👠", "high-heeled shoe", listOf("clothing", "heel", "high-heeled shoe", "shoe", "woman")),
    EmojiEntry("👡", "womans sandal", listOf("clothing", "sandal", "shoe", "woman", "womans sandal")),
    EmojiEntry("🩰", "ballet shoes", listOf("ballet", "ballet shoes", "dance")),
    EmojiEntry("👢", "womans boot", listOf("boot", "clothing", "shoe", "woman", "womans boot")),
    EmojiEntry("👑", "crown", listOf("clothing", "crown", "king", "queen")),
    EmojiEntry("👒", "womans hat", listOf("clothing", "hat", "woman", "womans hat")),
    EmojiEntry("🎩", "top hat", listOf("clothing", "hat", "top", "tophat")),
    EmojiEntry("🎓", "graduation cap", listOf("cap", "celebration", "clothing", "graduation", "hat")),
    EmojiEntry("🧢", "billed cap", listOf("baseball cap", "billed cap")),
    EmojiEntry("🪖", "military helmet", listOf("army", "helmet", "military", "soldier", "warrior")),
    EmojiEntry("⛑", "rescue workers helmet", listOf("aid", "cross", "face", "hat", "helmet", "rescue workers helmet")),
    EmojiEntry("📿", "prayer beads", listOf("beads", "clothing", "necklace", "prayer", "religion")),
    EmojiEntry("💄", "lipstick", listOf("cosmetics", "lipstick", "makeup")),
    EmojiEntry("💍", "ring", listOf("diamond", "ring")),
    EmojiEntry("💎", "gem stone", listOf("diamond", "gem", "gem stone", "jewel")),
    EmojiEntry("🔇", "muted speaker", listOf("mute", "muted speaker", "quiet", "silent", "speaker")),
    EmojiEntry("🔈", "speaker low volume", listOf("soft", "speaker low volume")),
    EmojiEntry("🔉", "speaker medium volume", listOf("medium", "speaker medium volume")),
    EmojiEntry("🔊", "speaker high volume", listOf("loud", "speaker high volume")),
    EmojiEntry("📢", "loudspeaker", listOf("loud", "loudspeaker", "public address")),
    EmojiEntry("📣", "megaphone", listOf("cheering", "megaphone")),
    EmojiEntry("📯", "postal horn", listOf("horn", "post", "postal")),
    EmojiEntry("🔔", "bell", listOf("bell")),
    EmojiEntry("🔕", "bell with slash", listOf("bell", "bell with slash", "forbidden", "mute", "quiet", "silent")),
    EmojiEntry("🎼", "musical score", listOf("music", "musical score", "score")),
    EmojiEntry("🎵", "musical note", listOf("music", "musical note", "note")),
    EmojiEntry("🎶", "musical notes", listOf("music", "musical notes", "note", "notes")),
    EmojiEntry("🎙", "studio microphone", listOf("mic", "microphone", "music", "studio")),
    EmojiEntry("🎚", "level slider", listOf("level", "music", "slider")),
    EmojiEntry("🎛", "control knobs", listOf("control", "knobs", "music")),
    EmojiEntry("🎤", "microphone", listOf("karaoke", "mic", "microphone")),
    EmojiEntry("🎧", "headphone", listOf("earbud", "headphone")),
    EmojiEntry("📻", "radio", listOf("radio", "video")),
    EmojiEntry("🎷", "saxophone", listOf("instrument", "music", "sax", "saxophone")),
    EmojiEntry("🪗", "accordion", listOf("accordion", "concertina", "squeeze box")),
    EmojiEntry("🎸", "guitar", listOf("guitar", "instrument", "music")),
    EmojiEntry("🎹", "musical keyboard", listOf("instrument", "keyboard", "music", "musical keyboard", "piano")),
    EmojiEntry("🎺", "trumpet", listOf("instrument", "music", "trumpet")),
    EmojiEntry("🎻", "violin", listOf("instrument", "music", "violin")),
    EmojiEntry("🪕", "banjo", listOf("banjo", "music", "stringed")),
    EmojiEntry("🥁", "drum", listOf("drum", "drumsticks", "music")),
    EmojiEntry("🪘", "long drum", listOf("beat", "conga", "drum", "long drum", "rhythm")),
    EmojiEntry("📱", "mobile phone", listOf("cell", "mobile", "phone", "telephone")),
    EmojiEntry("📲", "mobile phone with arrow", listOf("arrow", "cell", "mobile", "mobile phone with arrow", "phone", "receive")),
    EmojiEntry("☎", "telephone", listOf("phone", "telephone")),
    EmojiEntry("📞", "telephone receiver", listOf("phone", "receiver", "telephone")),
    EmojiEntry("📟", "pager", listOf("pager")),
    EmojiEntry("📠", "fax machine", listOf("fax", "fax machine")),
    EmojiEntry("🔋", "battery", listOf("battery")),
    EmojiEntry("🔌", "electric plug", listOf("electric", "electricity", "plug")),
    EmojiEntry("💻", "laptop", listOf("computer", "laptop", "pc", "personal")),
    EmojiEntry("🖥", "desktop computer", listOf("computer", "desktop")),
    EmojiEntry("🖨", "printer", listOf("computer", "printer")),
    EmojiEntry("⌨", "keyboard", listOf("computer", "keyboard")),
    EmojiEntry("🖱", "computer mouse", listOf("computer", "computer mouse")),
    EmojiEntry("🖲", "trackball", listOf("computer", "trackball")),
    EmojiEntry("💽", "computer disk", listOf("computer", "disk", "minidisk", "optical")),
    EmojiEntry("💾", "floppy disk", listOf("computer", "disk", "floppy")),
    EmojiEntry("💿", "optical disk", listOf("cd", "computer", "disk", "optical")),
    EmojiEntry("📀", "dvd", listOf("blu-ray", "computer", "disk", "dvd", "optical")),
    EmojiEntry("🧮", "abacus", listOf("abacus", "calculation")),
    EmojiEntry("🎥", "movie camera", listOf("camera", "cinema", "movie")),
    EmojiEntry("🎞", "film frames", listOf("cinema", "film", "frames", "movie")),
    EmojiEntry("📽", "film projector", listOf("cinema", "film", "movie", "projector", "video")),
    EmojiEntry("🎬", "clapper board", listOf("clapper", "clapper board", "movie")),
    EmojiEntry("📺", "television", listOf("television", "tv", "video")),
    EmojiEntry("📷", "camera", listOf("camera", "video")),
    EmojiEntry("📸", "camera with flash", listOf("camera", "camera with flash", "flash", "video")),
    EmojiEntry("📹", "video camera", listOf("camera", "video")),
    EmojiEntry("📼", "videocassette", listOf("tape", "vhs", "video", "videocassette")),
    EmojiEntry("🔍", "magnifying glass tilted left", listOf("glass", "magnifying", "magnifying glass tilted left", "search", "tool")),
    EmojiEntry("🔎", "magnifying glass tilted right", listOf("glass", "magnifying", "magnifying glass tilted right", "search", "tool")),
    EmojiEntry("🕯", "candle", listOf("candle", "light")),
    EmojiEntry("💡", "light bulb", listOf("bulb", "comic", "electric", "idea", "light")),
    EmojiEntry("🔦", "flashlight", listOf("electric", "flashlight", "light", "tool", "torch")),
    EmojiEntry("🏮", "red paper lantern", listOf("bar", "lantern", "light", "red", "red paper lantern")),
    EmojiEntry("🪔", "diya lamp", listOf("diya", "lamp", "oil")),
    EmojiEntry("📔", "notebook with decorative cover", listOf("book", "cover", "decorated", "notebook", "notebook with decorative cover")),
    EmojiEntry("📕", "closed book", listOf("book", "closed")),
    EmojiEntry("📖", "open book", listOf("book", "open")),
    EmojiEntry("📗", "green book", listOf("book", "green")),
    EmojiEntry("📘", "blue book", listOf("blue", "book")),
    EmojiEntry("📙", "orange book", listOf("book", "orange")),
    EmojiEntry("📚", "books", listOf("book", "books")),
    EmojiEntry("📓", "notebook", listOf("notebook")),
    EmojiEntry("📒", "ledger", listOf("ledger", "notebook")),
    EmojiEntry("📃", "page with curl", listOf("curl", "document", "page", "page with curl")),
    EmojiEntry("📜", "scroll", listOf("paper", "scroll")),
    EmojiEntry("📄", "page facing up", listOf("document", "page", "page facing up")),
    EmojiEntry("📰", "newspaper", listOf("news", "newspaper", "paper")),
    EmojiEntry("🗞", "rolled-up newspaper", listOf("news", "newspaper", "paper", "rolled", "rolled-up newspaper")),
    EmojiEntry("📑", "bookmark tabs", listOf("bookmark", "mark", "marker", "tabs")),
    EmojiEntry("🔖", "bookmark", listOf("bookmark", "mark")),
)
