package com.zacksimpson.emojis

// Auto-generated from the RN app's utils/emojiData.ts via scripts/convert-emoji-index.js — do not hand-edit.
// Part 10/13 of EMOJI_INDEX, split across files so each file's <clinit> stays under the JVM's 64KB method size limit.
internal val EMOJI_INDEX_PART_9: List<EmojiEntry> = listOf(
    EmojiEntry("🔞", "no one under eighteen", listOf("18", "age restriction", "eighteen", "no one under eighteen", "prohibited", "underage")),
    EmojiEntry("☢", "radioactive", listOf("radioactive", "sign")),
    EmojiEntry("☣", "biohazard", listOf("biohazard", "sign")),
    EmojiEntry("⬆", "up arrow", listOf("arrow", "cardinal", "direction", "north", "up arrow")),
    EmojiEntry("↗", "up-right arrow", listOf("arrow", "direction", "intercardinal", "northeast", "up-right arrow")),
    EmojiEntry("➡", "right arrow", listOf("arrow", "cardinal", "direction", "east", "right arrow")),
    EmojiEntry("↘", "down-right arrow", listOf("arrow", "direction", "down-right arrow", "intercardinal", "southeast")),
    EmojiEntry("⬇", "down arrow", listOf("arrow", "cardinal", "direction", "down", "south")),
    EmojiEntry("↙", "down-left arrow", listOf("arrow", "direction", "down-left arrow", "intercardinal", "southwest")),
    EmojiEntry("⬅", "left arrow", listOf("arrow", "cardinal", "direction", "left arrow", "west")),
    EmojiEntry("↖", "up-left arrow", listOf("arrow", "direction", "intercardinal", "northwest", "up-left arrow")),
    EmojiEntry("↕", "up-down arrow", listOf("arrow", "up-down arrow")),
    EmojiEntry("↔", "left-right arrow", listOf("arrow", "left-right arrow")),
    EmojiEntry("↩", "right arrow curving left", listOf("arrow", "right arrow curving left")),
    EmojiEntry("↪", "left arrow curving right", listOf("arrow", "left arrow curving right")),
    EmojiEntry("⤴", "right arrow curving up", listOf("arrow", "right arrow curving up")),
    EmojiEntry("⤵", "right arrow curving down", listOf("arrow", "down", "right arrow curving down")),
    EmojiEntry("🔃", "clockwise vertical arrows", listOf("arrow", "clockwise", "clockwise vertical arrows", "reload")),
    EmojiEntry("🔄", "counterclockwise arrows button", listOf("anticlockwise", "arrow", "counterclockwise", "counterclockwise arrows button", "withershins")),
    EmojiEntry("🔙", "BACK arrow", listOf("arrow", "back", "BACK arrow")),
    EmojiEntry("🔚", "END arrow", listOf("arrow", "end", "END arrow")),
    EmojiEntry("🔛", "ON! arrow", listOf("arrow", "mark", "on", "ON! arrow")),
    EmojiEntry("🔜", "SOON arrow", listOf("arrow", "soon", "SOON arrow")),
    EmojiEntry("🔝", "TOP arrow", listOf("arrow", "top", "TOP arrow", "up")),
    EmojiEntry("🛐", "place of worship", listOf("place of worship", "religion", "worship")),
    EmojiEntry("⚛", "atom symbol", listOf("atheist", "atom", "atom symbol")),
    EmojiEntry("🕉", "om", listOf("Hindu", "om", "religion")),
    EmojiEntry("✡", "star of David", listOf("David", "Jew", "Jewish", "religion", "star", "star of David")),
    EmojiEntry("☸", "wheel of dharma", listOf("Buddhist", "dharma", "religion", "wheel", "wheel of dharma")),
    EmojiEntry("☯", "yin yang", listOf("religion", "tao", "taoist", "yang", "yin")),
    EmojiEntry("✝", "latin cross", listOf("Christian", "cross", "latin cross", "religion")),
    EmojiEntry("☦", "orthodox cross", listOf("Christian", "cross", "orthodox cross", "religion")),
    EmojiEntry("☪", "star and crescent", listOf("islam", "Muslim", "religion", "star and crescent")),
    EmojiEntry("☮", "peace symbol", listOf("peace", "peace symbol")),
    EmojiEntry("🕎", "menorah", listOf("candelabrum", "candlestick", "menorah", "religion")),
    EmojiEntry("🔯", "dotted six-pointed star", listOf("dotted six-pointed star", "fortune", "star")),
    EmojiEntry("♈", "Aries", listOf("Aries", "ram", "zodiac")),
    EmojiEntry("♉", "Taurus", listOf("bull", "ox", "Taurus", "zodiac")),
    EmojiEntry("♊", "Gemini", listOf("Gemini", "twins", "zodiac")),
    EmojiEntry("♋", "Cancer", listOf("Cancer", "crab", "zodiac")),
    EmojiEntry("♌", "Leo", listOf("Leo", "lion", "zodiac")),
    EmojiEntry("♍", "Virgo", listOf("Virgo", "zodiac")),
    EmojiEntry("♎", "Libra", listOf("balance", "justice", "Libra", "scales", "zodiac")),
    EmojiEntry("♏", "Scorpio", listOf("Scorpio", "scorpion", "scorpius", "zodiac")),
    EmojiEntry("♐", "Sagittarius", listOf("archer", "Sagittarius", "zodiac")),
    EmojiEntry("♑", "Capricorn", listOf("Capricorn", "goat", "zodiac")),
    EmojiEntry("♒", "Aquarius", listOf("Aquarius", "bearer", "water", "zodiac")),
    EmojiEntry("♓", "Pisces", listOf("fish", "Pisces", "zodiac")),
    EmojiEntry("⛎", "Ophiuchus", listOf("bearer", "Ophiuchus", "serpent", "snake", "zodiac")),
    EmojiEntry("🔀", "shuffle tracks button", listOf("arrow", "crossed", "shuffle tracks button")),
    EmojiEntry("🔁", "repeat button", listOf("arrow", "clockwise", "repeat", "repeat button")),
    EmojiEntry("🔂", "repeat single button", listOf("arrow", "clockwise", "once", "repeat single button")),
    EmojiEntry("▶", "play button", listOf("arrow", "play", "play button", "right", "triangle")),
    EmojiEntry("⏩", "fast-forward button", listOf("arrow", "double", "fast", "fast-forward button", "forward")),
    EmojiEntry("⏭", "next track button", listOf("arrow", "next scene", "next track", "next track button", "triangle")),
    EmojiEntry("⏯", "play or pause button", listOf("arrow", "pause", "play", "play or pause button", "right", "triangle")),
    EmojiEntry("◀", "reverse button", listOf("arrow", "left", "reverse", "reverse button", "triangle")),
    EmojiEntry("⏪", "fast reverse button", listOf("arrow", "double", "fast reverse button", "rewind")),
    EmojiEntry("⏮", "last track button", listOf("arrow", "last track button", "previous scene", "previous track", "triangle")),
    EmojiEntry("🔼", "upwards button", listOf("arrow", "button", "red", "upwards button")),
    EmojiEntry("⏫", "fast up button", listOf("arrow", "double", "fast up button")),
    EmojiEntry("🔽", "downwards button", listOf("arrow", "button", "down", "downwards button", "red")),
    EmojiEntry("⏬", "fast down button", listOf("arrow", "double", "down", "fast down button")),
    EmojiEntry("⏸", "pause button", listOf("bar", "double", "pause", "pause button", "vertical")),
    EmojiEntry("⏹", "stop button", listOf("square", "stop", "stop button")),
    EmojiEntry("⏺", "record button", listOf("circle", "record", "record button")),
    EmojiEntry("⏏", "eject button", listOf("eject", "eject button")),
    EmojiEntry("🎦", "cinema", listOf("camera", "cinema", "film", "movie")),
    EmojiEntry("🔅", "dim button", listOf("brightness", "dim", "dim button", "low")),
    EmojiEntry("🔆", "bright button", listOf("bright", "bright button", "brightness")),
    EmojiEntry("📶", "antenna bars", listOf("antenna", "antenna bars", "bar", "cell", "mobile", "phone")),
    EmojiEntry("📳", "vibration mode", listOf("cell", "mobile", "mode", "phone", "telephone", "vibration")),
    EmojiEntry("📴", "mobile phone off", listOf("cell", "mobile", "off", "phone", "telephone")),
    EmojiEntry("♀", "female sign", listOf("female sign", "woman")),
    EmojiEntry("♂", "male sign", listOf("male sign", "man")),
    EmojiEntry("⚧", "transgender symbol", listOf("transgender", "transgender symbol")),
    EmojiEntry("✖", "multiply", listOf("×", "cancel", "multiplication", "multiply", "sign", "x")),
    EmojiEntry("➕", "plus", listOf("+", "math", "plus", "sign")),
    EmojiEntry("➖", "minus", listOf("-", "?", "math", "minus", "sign")),
    EmojiEntry("➗", "divide", listOf("÷", "divide", "division", "math", "sign")),
    EmojiEntry("♾", "infinity", listOf("forever", "infinity", "unbounded", "universal")),
    EmojiEntry("‼", "double exclamation mark", listOf("!", "!!", "bangbang", "double exclamation mark", "exclamation", "mark")),
    EmojiEntry("⁉", "exclamation question mark", listOf("!", "!?", "?", "exclamation", "interrobang", "mark", "punctuation", "question")),
    EmojiEntry("❓", "red question mark", listOf("?", "mark", "punctuation", "question", "red question mark")),
    EmojiEntry("❔", "white question mark", listOf("?", "mark", "outlined", "punctuation", "question", "white question mark")),
    EmojiEntry("❕", "white exclamation mark", listOf("!", "exclamation", "mark", "outlined", "punctuation", "white exclamation mark")),
    EmojiEntry("❗", "red exclamation mark", listOf("!", "exclamation", "mark", "punctuation", "red exclamation mark")),
    EmojiEntry("〰", "wavy dash", listOf("dash", "punctuation", "wavy")),
    EmojiEntry("💱", "currency exchange", listOf("bank", "currency", "exchange", "money")),
    EmojiEntry("💲", "heavy dollar sign", listOf("currency", "dollar", "heavy dollar sign", "money")),
    EmojiEntry("⚕", "medical symbol", listOf("aesculapius", "medical symbol", "medicine", "staff")),
    EmojiEntry("♻", "recycling symbol", listOf("recycle", "recycling symbol")),
    EmojiEntry("⚜", "fleur-de-lis", listOf("fleur-de-lis")),
    EmojiEntry("🔱", "trident emblem", listOf("anchor", "emblem", "ship", "tool", "trident")),
    EmojiEntry("📛", "name badge", listOf("badge", "name")),
    EmojiEntry("🔰", "Japanese symbol for beginner", listOf("beginner", "chevron", "Japanese", "Japanese symbol for beginner", "leaf")),
    EmojiEntry("⭕", "hollow red circle", listOf("circle", "hollow red circle", "large", "o", "red")),
    EmojiEntry("✅", "check mark button", listOf("?", "button", "check", "mark")),
    EmojiEntry("☑", "check box with check", listOf("?", "box", "check", "check box with check")),
    EmojiEntry("✔", "check mark", listOf("?", "check", "mark")),
    EmojiEntry("❌", "cross mark", listOf("×", "cancel", "cross", "mark", "multiplication", "multiply", "x")),
    EmojiEntry("❎", "cross mark button", listOf("×", "cross mark button", "mark", "square", "x")),
    EmojiEntry("➰", "curly loop", listOf("curl", "curly loop", "loop")),
    EmojiEntry("➿", "double curly loop", listOf("curl", "double", "double curly loop", "loop")),
    EmojiEntry("〽", "part alternation mark", listOf("mark", "part", "part alternation mark")),
    EmojiEntry("✳", "eight-spoked asterisk", listOf("*", "asterisk", "eight-spoked asterisk")),
    EmojiEntry("✴", "eight-pointed star", listOf("*", "eight-pointed star", "star")),
    EmojiEntry("❇", "sparkle", listOf("*", "sparkle")),
    EmojiEntry("©", "copyright", listOf("c", "copyright")),
    EmojiEntry("®", "registered", listOf("r", "registered")),
    EmojiEntry("™", "trade mark", listOf("mark", "tm", "trade mark", "trademark")),
    EmojiEntry("#️⃣", "keycap: #", listOf("keycap")),
    EmojiEntry("*️⃣", "keycap: *", listOf("keycap")),
    EmojiEntry("0️⃣", "keycap: 0", listOf("keycap")),
    EmojiEntry("1️⃣", "keycap: 1", listOf("keycap")),
    EmojiEntry("2️⃣", "keycap: 2", listOf("keycap")),
    EmojiEntry("3️⃣", "keycap: 3", listOf("keycap")),
    EmojiEntry("4️⃣", "keycap: 4", listOf("keycap")),
    EmojiEntry("5️⃣", "keycap: 5", listOf("keycap")),
    EmojiEntry("6️⃣", "keycap: 6", listOf("keycap")),
    EmojiEntry("7️⃣", "keycap: 7", listOf("keycap")),
    EmojiEntry("8️⃣", "keycap: 8", listOf("keycap")),
    EmojiEntry("9️⃣", "keycap: 9", listOf("keycap")),
    EmojiEntry("🔟", "keycap: 10", listOf("keycap")),
    EmojiEntry("🔠", "input latin uppercase", listOf("ABCD", "input", "latin", "letters", "uppercase")),
    EmojiEntry("🔡", "input latin lowercase", listOf("abcd", "input", "latin", "letters", "lowercase")),
    EmojiEntry("🔢", "input numbers", listOf("1234", "input", "numbers")),
    EmojiEntry("🔣", "input symbols", listOf("??&%", "input", "input symbols")),
    EmojiEntry("🔤", "input latin letters", listOf("abc", "alphabet", "input", "latin", "letters")),
    EmojiEntry("🅰", "A button (blood type)", listOf("a", "A button (blood type)", "blood type")),
    EmojiEntry("🆎", "AB button (blood type)", listOf("ab", "AB button (blood type)", "blood type")),
    EmojiEntry("🅱", "B button (blood type)", listOf("b", "B button (blood type)", "blood type")),
    EmojiEntry("🆑", "CL button", listOf("cl", "CL button")),
    EmojiEntry("🆒", "COOL button", listOf("cool", "COOL button")),
    EmojiEntry("🆓", "FREE button", listOf("free", "FREE button")),
    EmojiEntry("ℹ", "information", listOf("i", "information")),
    EmojiEntry("🆔", "ID button", listOf("id", "ID button", "identity")),
    EmojiEntry("Ⓜ", "circled M", listOf("circle", "circled M", "m")),
    EmojiEntry("🆕", "NEW button", listOf("new", "NEW button")),
    EmojiEntry("🆖", "NG button", listOf("ng", "NG button")),
    EmojiEntry("🅾", "O button (blood type)", listOf("blood type", "o", "O button (blood type)")),
    EmojiEntry("🆗", "OK button", listOf("OK", "OK button")),
    EmojiEntry("🅿", "P button", listOf("P button", "parking")),
    EmojiEntry("🆘", "SOS button", listOf("help", "sos", "SOS button")),
    EmojiEntry("🆙", "UP! button", listOf("mark", "up", "UP! button")),
    EmojiEntry("🆚", "VS button", listOf("versus", "vs", "VS button")),
    EmojiEntry("🈁", "Japanese here button", listOf("here", "Japanese", "Japanese here button", "katakana", "??")),
    EmojiEntry("🈂", "Japanese service charge button", listOf("service charge", "Japanese", "Japanese service charge button", "katakana", "?")),
    EmojiEntry("🈷", "Japanese monthly amount button", listOf("monthly amount", "ideograph", "Japanese", "Japanese monthly amount button", "?")),
    EmojiEntry("🈶", "Japanese not free of charge button", listOf("not free of charge", "ideograph", "Japanese", "Japanese not free of charge button", "?")),
)
