package com.zacksimpson.emojis

// Auto-generated from the RN app's utils/emojiData.ts via scripts/convert-emoji-index.js — do not hand-edit.
// Part 2/13 of EMOJI_INDEX, split across files so each file's <clinit> stays under the JVM's 64KB method size limit.
internal val EMOJI_INDEX_PART_1: List<EmojiEntry> = listOf(
    EmojiEntry("💬", "speech balloon", listOf("balloon", "bubble", "comic", "dialog", "speech")),
    EmojiEntry("👁️‍🗨️", "eye in speech bubble", listOf("eye", "eye in speech bubble", "speech bubble", "witness")),
    EmojiEntry("🗨", "left speech bubble", listOf("dialog", "left speech bubble", "speech")),
    EmojiEntry("🗯", "right anger bubble", listOf("angry", "balloon", "bubble", "mad", "right anger bubble")),
    EmojiEntry("💭", "thought balloon", listOf("balloon", "bubble", "comic", "thought")),
    EmojiEntry("💤", "zzz", listOf("comic", "sleep", "zzz")),
    EmojiEntry("👋", "waving hand", listOf("hand", "wave", "waving")),
    EmojiEntry("🤚", "raised back of hand", listOf("backhand", "raised", "raised back of hand")),
    EmojiEntry("🖐", "hand with fingers splayed", listOf("finger", "hand", "hand with fingers splayed", "splayed")),
    EmojiEntry("✋", "raised hand", listOf("hand", "high 5", "high five", "raised hand")),
    EmojiEntry("🖖", "vulcan salute", listOf("finger", "hand", "spock", "vulcan", "vulcan salute")),
    EmojiEntry("👌", "OK hand", listOf("hand", "OK")),
    EmojiEntry("🤌", "pinched fingers", listOf("fingers", "hand gesture", "interrogation", "pinched", "sarcastic")),
    EmojiEntry("🤏", "pinching hand", listOf("pinching hand", "small amount")),
    EmojiEntry("✌", "victory hand", listOf("hand", "v", "victory")),
    EmojiEntry("🤞", "crossed fingers", listOf("cross", "crossed fingers", "finger", "hand", "luck")),
    EmojiEntry("🤟", "love-you gesture", listOf("hand", "ILY", "love-you gesture")),
    EmojiEntry("🤘", "sign of the horns", listOf("finger", "hand", "horns", "rock-on", "sign of the horns")),
    EmojiEntry("🤙", "call me hand", listOf("call", "call me hand", "hand")),
    EmojiEntry("👈", "backhand index pointing left", listOf("backhand", "backhand index pointing left", "finger", "hand", "index", "point")),
    EmojiEntry("👉", "backhand index pointing right", listOf("backhand", "backhand index pointing right", "finger", "hand", "index", "point")),
    EmojiEntry("👆", "backhand index pointing up", listOf("backhand", "backhand index pointing up", "finger", "hand", "point", "up")),
    EmojiEntry("🖕", "middle finger", listOf("finger", "hand", "middle finger")),
    EmojiEntry("👇", "backhand index pointing down", listOf("backhand", "backhand index pointing down", "down", "finger", "hand", "point")),
    EmojiEntry("☝", "index pointing up", listOf("finger", "hand", "index", "index pointing up", "point", "up")),
    EmojiEntry("👍", "thumbs up", listOf("+1", "hand", "thumb", "thumbs up", "up")),
    EmojiEntry("👎", "thumbs down", listOf("-1", "down", "hand", "thumb", "thumbs down")),
    EmojiEntry("✊", "raised fist", listOf("clenched", "fist", "hand", "punch", "raised fist")),
    EmojiEntry("👊", "oncoming fist", listOf("clenched", "fist", "hand", "oncoming fist", "punch")),
    EmojiEntry("🤛", "left-facing fist", listOf("fist", "left-facing fist", "leftwards")),
    EmojiEntry("🤜", "right-facing fist", listOf("fist", "right-facing fist", "rightwards")),
    EmojiEntry("👏", "clapping hands", listOf("clap", "clapping hands", "hand")),
    EmojiEntry("🙌", "raising hands", listOf("celebration", "gesture", "hand", "hooray", "raised", "raising hands", "praise")),
    EmojiEntry("👐", "open hands", listOf("hand", "open", "open hands")),
    EmojiEntry("🤲", "palms up together", listOf("palms up together", "prayer", "cupped hands")),
    EmojiEntry("🤝", "handshake", listOf("agreement", "hand", "handshake", "meeting", "shake")),
    EmojiEntry("🙏", "folded hands", listOf("ask", "folded hands", "hand", "high 5", "high five", "please", "pray", "thanks", "praise")),
    EmojiEntry("✍", "writing hand", listOf("hand", "write", "writing hand")),
    EmojiEntry("💅", "nail polish", listOf("care", "cosmetics", "manicure", "nail", "polish")),
    EmojiEntry("🤳", "selfie", listOf("camera", "phone", "selfie")),
    EmojiEntry("💪", "flexed biceps", listOf("biceps", "comic", "flex", "flexed biceps", "muscle")),
    EmojiEntry("🦾", "mechanical arm", listOf("accessibility", "mechanical arm", "prosthetic")),
    EmojiEntry("🦿", "mechanical leg", listOf("accessibility", "mechanical leg", "prosthetic")),
    EmojiEntry("🦵", "leg", listOf("kick", "leg", "limb")),
    EmojiEntry("🦶", "foot", listOf("foot", "kick", "stomp")),
    EmojiEntry("👂", "ear", listOf("body", "ear")),
    EmojiEntry("🦻", "ear with hearing aid", listOf("accessibility", "ear with hearing aid", "hard of hearing")),
    EmojiEntry("👃", "nose", listOf("body", "nose")),
    EmojiEntry("🧠", "brain", listOf("brain", "intelligent")),
    EmojiEntry("🫀", "anatomical heart", listOf("anatomical", "cardiology", "heart", "organ", "pulse")),
    EmojiEntry("🫁", "lungs", listOf("breath", "exhalation", "inhalation", "lungs", "organ", "respiration")),
    EmojiEntry("🦷", "tooth", listOf("dentist", "tooth")),
    EmojiEntry("🦴", "bone", listOf("bone", "skeleton")),
    EmojiEntry("👀", "eyes", listOf("eye", "eyes", "face")),
    EmojiEntry("👁", "eye", listOf("body", "eye")),
    EmojiEntry("👅", "tongue", listOf("body", "tongue")),
    EmojiEntry("👄", "mouth", listOf("lips", "mouth")),
    EmojiEntry("👶", "baby", listOf("baby", "young")),
    EmojiEntry("🧒", "child", listOf("child", "gender-neutral", "unspecified gender", "young")),
    EmojiEntry("👦", "boy", listOf("boy", "young")),
    EmojiEntry("👧", "girl", listOf("girl", "Virgo", "young", "zodiac")),
    EmojiEntry("🧑", "person", listOf("adult", "gender-neutral", "person", "unspecified gender")),
    EmojiEntry("👱", "person: blond hair", listOf("blond", "blond-haired person", "hair", "person: blond hair")),
    EmojiEntry("👨", "man", listOf("adult", "man")),
    EmojiEntry("🧔", "person: beard", listOf("beard", "person", "person: beard", "bewhiskered")),
    EmojiEntry("🧔‍♂️", "? man: beard", listOf("beard", "man", "man: beard")),
    EmojiEntry("🧔‍♀️", "? woman: beard", listOf("beard", "woman", "woman: beard")),
    EmojiEntry("👨‍🦰", "man: red hair", listOf("adult", "man", "red hair")),
    EmojiEntry("👨‍🦱", "man: curly hair", listOf("adult", "curly hair", "man")),
    EmojiEntry("👨‍🦳", "man: white hair", listOf("adult", "man", "white hair")),
    EmojiEntry("👨‍🦲", "man: bald", listOf("adult", "bald", "man")),
    EmojiEntry("👩", "woman", listOf("adult", "woman")),
    EmojiEntry("👩‍🦰", "woman: red hair", listOf("adult", "red hair", "woman")),
    EmojiEntry("🧑‍🦰", "person: red hair", listOf("adult", "gender-neutral", "person", "red hair", "unspecified gender")),
    EmojiEntry("👩‍🦱", "woman: curly hair", listOf("adult", "curly hair", "woman")),
    EmojiEntry("🧑‍🦱", "person: curly hair", listOf("adult", "curly hair", "gender-neutral", "person", "unspecified gender")),
    EmojiEntry("👩‍🦳", "woman: white hair", listOf("adult", "white hair", "woman")),
    EmojiEntry("🧑‍🦳", "person: white hair", listOf("adult", "gender-neutral", "person", "unspecified gender", "white hair")),
    EmojiEntry("👩‍🦲", "woman: bald", listOf("adult", "bald", "woman")),
    EmojiEntry("🧑‍🦲", "person: bald", listOf("adult", "bald", "gender-neutral", "person", "unspecified gender")),
    EmojiEntry("👱‍♀️", "woman: blond hair", listOf("blond-haired woman", "blonde", "hair", "woman", "woman: blond hair")),
    EmojiEntry("👱‍♂️", "man: blond hair", listOf("blond", "blond-haired man", "hair", "man", "man: blond hair")),
    EmojiEntry("🧓", "older person", listOf("adult", "gender-neutral", "old", "older person", "unspecified gender")),
    EmojiEntry("👴", "old man", listOf("adult", "man", "old")),
    EmojiEntry("👵", "old woman", listOf("adult", "old", "woman")),
    EmojiEntry("🙍", "person frowning", listOf("frown", "gesture", "person frowning")),
    EmojiEntry("🙍‍♂️", "man frowning", listOf("frowning", "gesture", "man")),
    EmojiEntry("🙍‍♀️", "woman frowning", listOf("frowning", "gesture", "woman")),
    EmojiEntry("🙎", "person pouting", listOf("gesture", "person pouting", "pouting")),
    EmojiEntry("🙎‍♂️", "man pouting", listOf("gesture", "man", "pouting")),
    EmojiEntry("🙎‍♀️", "woman pouting", listOf("gesture", "pouting", "woman")),
    EmojiEntry("🙅", "person gesturing NO", listOf("forbidden", "gesture", "hand", "person gesturing NO", "prohibited")),
    EmojiEntry("🙅‍♂️", "man gesturing NO", listOf("forbidden", "gesture", "hand", "man", "man gesturing NO", "prohibited")),
    EmojiEntry("🙅‍♀️", "woman gesturing NO", listOf("forbidden", "gesture", "hand", "prohibited", "woman", "woman gesturing NO")),
    EmojiEntry("🙆", "person gesturing OK", listOf("gesture", "hand", "OK", "person gesturing OK")),
    EmojiEntry("🙆‍♂️", "man gesturing OK", listOf("gesture", "hand", "man", "man gesturing OK", "OK")),
    EmojiEntry("🙆‍♀️", "woman gesturing OK", listOf("gesture", "hand", "OK", "woman", "woman gesturing OK")),
    EmojiEntry("💁", "person tipping hand", listOf("hand", "help", "information", "person tipping hand", "sassy", "tipping")),
    EmojiEntry("💁‍♂️", "man tipping hand", listOf("man", "man tipping hand", "sassy", "tipping hand")),
    EmojiEntry("💁‍♀️", "woman tipping hand", listOf("sassy", "tipping hand", "woman", "woman tipping hand")),
    EmojiEntry("🙋", "person raising hand", listOf("gesture", "hand", "happy", "person raising hand", "raised")),
    EmojiEntry("🙋‍♂️", "man raising hand", listOf("gesture", "man", "man raising hand", "raising hand")),
    EmojiEntry("🙋‍♀️", "woman raising hand", listOf("gesture", "raising hand", "woman", "woman raising hand")),
    EmojiEntry("🧏", "deaf person", listOf("accessibility", "deaf", "deaf person", "ear", "hear")),
    EmojiEntry("🧏‍♂️", "deaf man", listOf("deaf", "man")),
    EmojiEntry("🧏‍♀️", "deaf woman", listOf("deaf", "woman")),
    EmojiEntry("🙇", "person bowing", listOf("apology", "bow", "gesture", "person bowing", "sorry")),
    EmojiEntry("🙇‍♂️", "man bowing", listOf("apology", "bowing", "favor", "gesture", "man", "sorry")),
    EmojiEntry("🙇‍♀️", "woman bowing", listOf("apology", "bowing", "favor", "gesture", "sorry", "woman")),
    EmojiEntry("🤦", "person facepalming", listOf("disbelief", "exasperation", "face", "palm", "person facepalming")),
    EmojiEntry("🤦‍♂️", "man facepalming", listOf("disbelief", "exasperation", "facepalm", "man", "man facepalming")),
    EmojiEntry("🤦‍♀️", "woman facepalming", listOf("disbelief", "exasperation", "facepalm", "woman", "woman facepalming")),
    EmojiEntry("🤷", "person shrugging", listOf("doubt", "ignorance", "indifference", "person shrugging", "shrug")),
    EmojiEntry("🤷‍♂️", "man shrugging", listOf("doubt", "ignorance", "indifference", "man", "man shrugging", "shrug")),
    EmojiEntry("🤷‍♀️", "woman shrugging", listOf("doubt", "ignorance", "indifference", "shrug", "woman", "woman shrugging")),
    EmojiEntry("🧑‍⚕️", "health worker", listOf("doctor", "health worker", "healthcare", "nurse", "therapist")),
    EmojiEntry("👨‍⚕️", "man health worker", listOf("doctor", "healthcare", "man", "man health worker", "nurse", "therapist")),
    EmojiEntry("👩‍⚕️", "woman health worker", listOf("doctor", "healthcare", "nurse", "therapist", "woman", "woman health worker")),
    EmojiEntry("🧑‍🎓", "student", listOf("graduate", "student")),
    EmojiEntry("👨‍🎓", "man student", listOf("graduate", "man", "student")),
    EmojiEntry("👩‍🎓", "woman student", listOf("graduate", "student", "woman")),
    EmojiEntry("🧑‍🏫", "teacher", listOf("instructor", "professor", "teacher")),
    EmojiEntry("👨‍🏫", "man teacher", listOf("instructor", "man", "professor", "teacher")),
    EmojiEntry("👩‍🏫", "woman teacher", listOf("instructor", "professor", "teacher", "woman")),
    EmojiEntry("🧑‍⚖️", "judge", listOf("judge", "justice", "scales")),
    EmojiEntry("👨‍⚖️", "man judge", listOf("judge", "justice", "man", "scales")),
    EmojiEntry("👩‍⚖️", "woman judge", listOf("judge", "justice", "scales", "woman")),
    EmojiEntry("🧑‍🌾", "farmer", listOf("farmer", "gardener", "rancher")),
    EmojiEntry("👨‍🌾", "man farmer", listOf("farmer", "gardener", "man", "rancher")),
    EmojiEntry("👩‍🌾", "woman farmer", listOf("farmer", "gardener", "rancher", "woman")),
    EmojiEntry("🧑‍🍳", "cook", listOf("chef", "cook")),
    EmojiEntry("👨‍🍳", "man cook", listOf("chef", "cook", "man")),
    EmojiEntry("👩‍🍳", "woman cook", listOf("chef", "cook", "woman")),
    EmojiEntry("🧑‍🔧", "mechanic", listOf("electrician", "mechanic", "plumber", "tradesperson")),
    EmojiEntry("👨‍🔧", "man mechanic", listOf("electrician", "man", "mechanic", "plumber", "tradesperson")),
    EmojiEntry("👩‍🔧", "woman mechanic", listOf("electrician", "mechanic", "plumber", "tradesperson", "woman")),
    EmojiEntry("🧑‍🏭", "factory worker", listOf("assembly", "factory", "industrial", "worker")),
    EmojiEntry("👨‍🏭", "man factory worker", listOf("assembly", "factory", "industrial", "man", "worker")),
    EmojiEntry("👩‍🏭", "woman factory worker", listOf("assembly", "factory", "industrial", "woman", "worker")),
    EmojiEntry("🧑‍💼", "office worker", listOf("architect", "business", "manager", "office worker", "white-collar")),
    EmojiEntry("👨‍💼", "man office worker", listOf("architect", "business", "man", "man office worker", "manager", "white-collar")),
    EmojiEntry("👩‍💼", "woman office worker", listOf("architect", "business", "manager", "white-collar", "woman", "woman office worker")),
    EmojiEntry("🧑‍🔬", "scientist", listOf("biologist", "chemist", "engineer", "physicist", "scientist")),
    EmojiEntry("👨‍🔬", "man scientist", listOf("biologist", "chemist", "engineer", "man", "physicist", "scientist")),
    EmojiEntry("👩‍🔬", "woman scientist", listOf("biologist", "chemist", "engineer", "physicist", "scientist", "woman")),
    EmojiEntry("🧑‍💻", "technologist", listOf("coder", "developer", "inventor", "software", "technologist")),
    EmojiEntry("👨‍💻", "man technologist", listOf("coder", "developer", "inventor", "man", "software", "technologist")),
    EmojiEntry("👩‍💻", "woman technologist", listOf("coder", "developer", "inventor", "software", "technologist", "woman")),
    EmojiEntry("🧑‍🎤", "singer", listOf("actor", "entertainer", "rock", "singer", "star")),
    EmojiEntry("👨‍🎤", "man singer", listOf("actor", "entertainer", "man", "rock", "singer", "star")),
)
