package com.zacksimpson.emojis

// Auto-generated from the RN app's utils/emojiData.ts via scripts/convert-emoji-index.js — do not hand-edit.
// Part 1/13 of EMOJI_INDEX, split across files so each file's <clinit> stays under the JVM's 64KB method size limit.
internal val EMOJI_INDEX_PART_0: List<EmojiEntry> = listOf(
    EmojiEntry("😀", "grinning face", listOf("face", "grin", "grinning face")),
    EmojiEntry("😃", "grinning face with big eyes", listOf("face", "grinning face with big eyes", "mouth", "open", "smile")),
    EmojiEntry("😄", "grinning face with smiling eyes", listOf("eye", "face", "grinning face with smiling eyes", "mouth", "open", "smile")),
    EmojiEntry("😁", "beaming face with smiling eyes", listOf("beaming face with smiling eyes", "eye", "face", "grin", "smile")),
    EmojiEntry("😆", "grinning squinting face", listOf("face", "grinning squinting face", "laugh", "mouth", "satisfied", "smile")),
    EmojiEntry("😅", "grinning face with sweat", listOf("cold", "face", "grinning face with sweat", "open", "smile", "sweat")),
    EmojiEntry("🤣", "rolling on the floor laughing", listOf("face", "floor", "laugh", "rofl", "rolling", "rolling on the floor laughing", "rotfl")),
    EmojiEntry("😂", "face with tears of joy", listOf("face", "face with tears of joy", "joy", "laugh", "tear")),
    EmojiEntry("🙂", "slightly smiling face", listOf("face", "slightly smiling face", "smile")),
    EmojiEntry("🙃", "upside-down face", listOf("face", "upside-down")),
    EmojiEntry("😉", "winking face", listOf("face", "wink", "winking face")),
    EmojiEntry("😊", "smiling face with smiling eyes", listOf("blush", "eye", "face", "smile", "smiling face with smiling eyes")),
    EmojiEntry("😇", "smiling face with halo", listOf("angel", "face", "fantasy", "halo", "innocent", "smiling face with halo")),
    EmojiEntry("🥰", "smiling face with hearts", listOf("adore", "crush", "hearts", "in love", "smiling face with hearts")),
    EmojiEntry("😍", "smiling face with heart-eyes", listOf("eye", "face", "love", "smile", "smiling face with heart-eyes")),
    EmojiEntry("🤩", "star-struck", listOf("eyes", "face", "grinning", "star", "star-struck", "starry-eyed")),
    EmojiEntry("😘", "face blowing a kiss", listOf("face", "face blowing a kiss", "kiss")),
    EmojiEntry("😗", "kissing face", listOf("face", "kiss", "kissing face")),
    EmojiEntry("☺", "smiling face", listOf("face", "outlined", "relaxed", "smile", "smiling face")),
    EmojiEntry("😚", "kissing face with closed eyes", listOf("closed", "eye", "face", "kiss", "kissing face with closed eyes")),
    EmojiEntry("😙", "kissing face with smiling eyes", listOf("eye", "face", "kiss", "kissing face with smiling eyes", "smile")),
    EmojiEntry("🥲", "smiling face with tear", listOf("grateful", "proud", "relieved", "smiling", "smiling face with tear", "tear", "touched")),
    EmojiEntry("😋", "face savoring food", listOf("delicious", "face", "face savoring food", "savouring", "smile", "yum")),
    EmojiEntry("😛", "face with tongue", listOf("face", "face with tongue", "tongue")),
    EmojiEntry("😜", "winking face with tongue", listOf("eye", "face", "joke", "tongue", "wink", "winking face with tongue")),
    EmojiEntry("🤪", "zany face", listOf("eye", "goofy", "large", "small", "zany face")),
    EmojiEntry("😝", "squinting face with tongue", listOf("eye", "face", "horrible", "squinting face with tongue", "taste", "tongue")),
    EmojiEntry("🤑", "money-mouth face", listOf("face", "money", "money-mouth face", "mouth")),
    EmojiEntry("🤗", "hugging face", listOf("face", "hug", "hugging")),
    EmojiEntry("🤭", "face with hand over mouth", listOf("face with hand over mouth", "whoops", "shock", "sudden realization", "surprise")),
    EmojiEntry("🤫", "shushing face", listOf("quiet", "shush", "shushing face")),
    EmojiEntry("🤔", "thinking face", listOf("face", "thinking")),
    EmojiEntry("🤐", "zipper-mouth face", listOf("face", "mouth", "zipper", "zipper-mouth face")),
    EmojiEntry("🤨", "face with raised eyebrow", listOf("distrust", "face with raised eyebrow", "skeptic", "disapproval", "disbelief", "mild surprise", "scepticism")),
    EmojiEntry("😐", "neutral face", listOf("deadpan", "face", "meh", "neutral")),
    EmojiEntry("😑", "expressionless face", listOf("expressionless", "face", "inexpressive", "meh", "unexpressive")),
    EmojiEntry("😶", "face without mouth", listOf("face", "face without mouth", "mouth", "quiet", "silent")),
    EmojiEntry("😶‍🌫️", "? face in clouds", listOf("absentminded", "face in clouds", "face in the fog", "head in clouds")),
    EmojiEntry("😏", "smirking face", listOf("face", "smirk", "smirking face")),
    EmojiEntry("😒", "unamused face", listOf("face", "unamused", "unhappy")),
    EmojiEntry("🙄", "face with rolling eyes", listOf("eyeroll", "eyes", "face", "face with rolling eyes", "rolling")),
    EmojiEntry("😬", "grimacing face", listOf("face", "grimace", "grimacing face")),
    EmojiEntry("😮‍💨", "? face exhaling", listOf("exhale", "face exhaling", "gasp", "groan", "relief", "whisper", "whistle")),
    EmojiEntry("🤥", "lying face", listOf("face", "lie", "lying face", "pinocchio")),
    EmojiEntry("😌", "relieved face", listOf("face", "relieved")),
    EmojiEntry("😔", "pensive face", listOf("dejected", "face", "pensive")),
    EmojiEntry("😪", "sleepy face", listOf("face", "sleep", "sleepy face")),
    EmojiEntry("🤤", "drooling face", listOf("drooling", "face")),
    EmojiEntry("😴", "sleeping face", listOf("face", "sleep", "sleeping face", "zzz")),
    EmojiEntry("😷", "face with medical mask", listOf("cold", "doctor", "face", "face with medical mask", "mask", "sick")),
    EmojiEntry("🤒", "face with thermometer", listOf("face", "face with thermometer", "ill", "sick", "thermometer")),
    EmojiEntry("🤕", "face with head-bandage", listOf("bandage", "face", "face with head-bandage", "hurt", "injury")),
    EmojiEntry("🤢", "nauseated face", listOf("face", "nauseated", "vomit")),
    EmojiEntry("🤮", "face vomiting", listOf("face vomiting", "puke", "sick", "vomit")),
    EmojiEntry("🤧", "sneezing face", listOf("face", "gesundheit", "sneeze", "sneezing face")),
    EmojiEntry("🥵", "hot face", listOf("feverish", "heat stroke", "hot", "hot face", "red-faced", "sweating")),
    EmojiEntry("🥶", "cold face", listOf("blue-faced", "cold", "cold face", "freezing", "frostbite", "icicles")),
    EmojiEntry("🥴", "woozy face", listOf("dizzy", "intoxicated", "tipsy", "uneven eyes", "wavy mouth", "woozy face")),
    EmojiEntry("😵", "knocked-out face", listOf("dead", "face", "knocked out", "knocked-out face")),
    EmojiEntry("😵‍💫", "? face with spiral eyes", listOf("dizzy", "face with spiral eyes", "hypnotized", "spiral", "trouble", "whoa")),
    EmojiEntry("🤯", "exploding head", listOf("exploding head", "mind blown", "shocked")),
    EmojiEntry("🤠", "cowboy hat face", listOf("cowboy", "cowgirl", "face", "hat")),
    EmojiEntry("🥳", "partying face", listOf("celebration", "hat", "horn", "party", "partying face")),
    EmojiEntry("🥸", "disguised face", listOf("disguise", "disguised face", "face", "glasses", "incognito", "nose")),
    EmojiEntry("😎", "smiling face with sunglasses", listOf("bright", "cool", "face", "smiling face with sunglasses", "sun", "sunglasses")),
    EmojiEntry("🤓", "nerd face", listOf("face", "geek", "nerd")),
    EmojiEntry("🧐", "face with monocle", listOf("face with monocle", "stuffy", "wealthy")),
    EmojiEntry("😕", "confused face", listOf("confused", "face", "meh")),
    EmojiEntry("😟", "worried face", listOf("face", "worried")),
    EmojiEntry("🙁", "slightly frowning face", listOf("face", "frown", "slightly frowning face")),
    EmojiEntry("☹", "frowning face", listOf("face", "frown", "frowning face")),
    EmojiEntry("😮", "face with open mouth", listOf("face", "face with open mouth", "mouth", "open", "sympathy")),
    EmojiEntry("😯", "hushed face", listOf("face", "hushed", "stunned", "surprised")),
    EmojiEntry("😲", "astonished face", listOf("astonished", "face", "shocked", "totally")),
    EmojiEntry("😳", "flushed face", listOf("dazed", "face", "flushed")),
    EmojiEntry("🥺", "pleading face", listOf("begging", "mercy", "pleading face", "puppy eyes")),
    EmojiEntry("😦", "frowning face with open mouth", listOf("face", "frown", "frowning face with open mouth", "mouth", "open")),
    EmojiEntry("😧", "anguished face", listOf("anguished", "face")),
    EmojiEntry("😨", "fearful face", listOf("face", "fear", "fearful", "scared")),
    EmojiEntry("😰", "anxious face with sweat", listOf("anxious face with sweat", "blue", "cold", "face", "rushed", "sweat")),
    EmojiEntry("😥", "sad but relieved face", listOf("disappointed", "face", "relieved", "sad but relieved face", "whew")),
    EmojiEntry("😢", "crying face", listOf("cry", "crying face", "face", "sad", "tear")),
    EmojiEntry("😭", "loudly crying face", listOf("cry", "face", "loudly crying face", "sad", "sob", "tear")),
    EmojiEntry("😱", "face screaming in fear", listOf("face", "face screaming in fear", "fear", "munch", "scared", "scream")),
    EmojiEntry("😖", "confounded face", listOf("confounded", "face")),
    EmojiEntry("😣", "persevering face", listOf("face", "persevere", "persevering face")),
    EmojiEntry("😞", "disappointed face", listOf("disappointed", "face")),
    EmojiEntry("😓", "downcast face with sweat", listOf("cold", "downcast face with sweat", "face", "sweat")),
    EmojiEntry("😩", "weary face", listOf("face", "tired", "weary")),
    EmojiEntry("😫", "tired face", listOf("face", "tired")),
    EmojiEntry("🥱", "yawning face", listOf("bored", "tired", "yawn", "yawning face")),
    EmojiEntry("😤", "face with steam from nose", listOf("face", "face with steam from nose", "triumph", "won")),
    EmojiEntry("😡", "pouting face", listOf("angry", "face", "mad", "pouting", "rage", "red")),
    EmojiEntry("😠", "angry face", listOf("anger", "angry", "face", "mad")),
    EmojiEntry("🤬", "face with symbols on mouth", listOf("face with symbols on mouth", "swearing", "cursing")),
    EmojiEntry("😈", "smiling face with horns", listOf("face", "fairy tale", "fantasy", "horns", "smile", "smiling face with horns")),
    EmojiEntry("👿", "angry face with horns", listOf("angry face with horns", "demon", "devil", "face", "fantasy", "imp")),
    EmojiEntry("💀", "skull", listOf("death", "face", "fairy tale", "monster", "skull")),
    EmojiEntry("☠", "skull and crossbones", listOf("crossbones", "death", "face", "monster", "skull", "skull and crossbones")),
    EmojiEntry("💩", "pile of poo", listOf("dung", "face", "monster", "pile of poo", "poo", "poop")),
    EmojiEntry("🤡", "clown face", listOf("clown", "face")),
    EmojiEntry("👹", "ogre", listOf("creature", "face", "fairy tale", "fantasy", "monster", "ogre", "troll")),
    EmojiEntry("👺", "goblin", listOf("creature", "face", "fairy tale", "fantasy", "goblin", "monster")),
    EmojiEntry("👻", "ghost", listOf("creature", "face", "fairy tale", "fantasy", "ghost", "monster")),
    EmojiEntry("👽", "alien", listOf("alien", "creature", "extraterrestrial", "face", "fantasy", "ufo")),
    EmojiEntry("👾", "alien monster", listOf("alien", "creature", "extraterrestrial", "face", "monster", "ufo")),
    EmojiEntry("🤖", "robot", listOf("face", "monster", "robot")),
    EmojiEntry("😺", "grinning cat", listOf("cat", "face", "grinning", "mouth", "open", "smile")),
    EmojiEntry("😸", "grinning cat with smiling eyes", listOf("cat", "eye", "face", "grin", "grinning cat with smiling eyes", "smile")),
    EmojiEntry("😹", "cat with tears of joy", listOf("cat", "cat with tears of joy", "face", "joy", "tear")),
    EmojiEntry("😻", "smiling cat with heart-eyes", listOf("cat", "eye", "face", "heart", "love", "smile", "smiling cat with heart-eyes")),
    EmojiEntry("😼", "cat with wry smile", listOf("cat", "cat with wry smile", "face", "ironic", "smile", "wry")),
    EmojiEntry("😽", "kissing cat", listOf("cat", "eye", "face", "kiss", "kissing cat")),
    EmojiEntry("🙀", "weary cat", listOf("cat", "face", "oh", "surprised", "weary")),
    EmojiEntry("😿", "crying cat", listOf("cat", "cry", "crying cat", "face", "sad", "tear")),
    EmojiEntry("😾", "pouting cat", listOf("cat", "face", "pouting")),
    EmojiEntry("🙈", "see-no-evil monkey", listOf("evil", "face", "forbidden", "monkey", "see", "see-no-evil monkey")),
    EmojiEntry("🙉", "hear-no-evil monkey", listOf("evil", "face", "forbidden", "hear", "hear-no-evil monkey", "monkey")),
    EmojiEntry("🙊", "speak-no-evil monkey", listOf("evil", "face", "forbidden", "monkey", "speak", "speak-no-evil monkey")),
    EmojiEntry("💋", "kiss mark", listOf("kiss", "kiss mark", "lips")),
    EmojiEntry("💌", "love letter", listOf("heart", "letter", "love", "mail")),
    EmojiEntry("💘", "heart with arrow", listOf("arrow", "cupid", "heart with arrow")),
    EmojiEntry("💝", "heart with ribbon", listOf("heart with ribbon", "ribbon", "valentine")),
    EmojiEntry("💖", "sparkling heart", listOf("excited", "sparkle", "sparkling heart")),
    EmojiEntry("💗", "growing heart", listOf("excited", "growing", "growing heart", "nervous", "pulse")),
    EmojiEntry("💓", "beating heart", listOf("beating", "beating heart", "heartbeat", "pulsating")),
    EmojiEntry("💞", "revolving hearts", listOf("revolving", "revolving hearts")),
    EmojiEntry("💕", "two hearts", listOf("love", "two hearts")),
    EmojiEntry("💟", "heart decoration", listOf("heart", "heart decoration")),
    EmojiEntry("❣", "heart exclamation", listOf("exclamation", "heart exclamation", "mark", "punctuation")),
    EmojiEntry("💔", "broken heart", listOf("break", "broken", "broken heart")),
    EmojiEntry("❤️‍🔥", "? heart on fire", listOf("burn", "heart", "heart on fire", "love", "lust", "sacred heart")),
    EmojiEntry("❤️‍🩹", "? mending heart", listOf("healthier", "improving", "mending", "mending heart", "recovering", "recuperating", "well")),
    EmojiEntry("❤", "red heart", listOf("heart", "red heart")),
    EmojiEntry("🧡", "orange heart", listOf("orange", "orange heart")),
    EmojiEntry("💛", "yellow heart", listOf("yellow", "yellow heart")),
    EmojiEntry("💚", "green heart", listOf("green", "green heart")),
    EmojiEntry("💙", "blue heart", listOf("blue", "blue heart")),
    EmojiEntry("💜", "purple heart", listOf("purple", "purple heart")),
    EmojiEntry("🤎", "brown heart", listOf("brown", "heart")),
    EmojiEntry("🖤", "black heart", listOf("black", "black heart", "evil", "wicked")),
    EmojiEntry("🤍", "white heart", listOf("heart", "white")),
    EmojiEntry("💯", "hundred points", listOf("100", "full", "hundred", "hundred points", "score")),
    EmojiEntry("💢", "anger symbol", listOf("anger symbol", "angry", "comic", "mad")),
    EmojiEntry("💥", "collision", listOf("boom", "collision", "comic")),
    EmojiEntry("💫", "dizzy", listOf("comic", "dizzy", "star")),
    EmojiEntry("💦", "sweat droplets", listOf("comic", "splashing", "sweat", "sweat droplets")),
    EmojiEntry("💨", "dashing away", listOf("comic", "dash", "dashing away", "running")),
    EmojiEntry("🕳", "hole", listOf("hole")),
    EmojiEntry("💣", "bomb", listOf("bomb", "comic")),
)
