package com.zacksimpson.emojis

// Auto-generated from the RN app's utils/emojiData.ts via scripts/convert-emoji-index.js — do not hand-edit.
// Part 4/13 of EMOJI_INDEX, split across files so each file's <clinit> stays under the JVM's 64KB method size limit.
internal val EMOJI_INDEX_PART_3: List<EmojiEntry> = listOf(
    EmojiEntry("🤽‍♀️", "woman playing water polo", listOf("water polo", "woman", "woman playing water polo")),
    EmojiEntry("🤾", "person playing handball", listOf("ball", "handball", "person playing handball")),
    EmojiEntry("🤾‍♂️", "man playing handball", listOf("handball", "man", "man playing handball")),
    EmojiEntry("🤾‍♀️", "woman playing handball", listOf("handball", "woman", "woman playing handball")),
    EmojiEntry("🤹", "person juggling", listOf("balance", "juggle", "multitask", "person juggling", "skill")),
    EmojiEntry("🤹‍♂️", "man juggling", listOf("juggling", "man", "multitask")),
    EmojiEntry("🤹‍♀️", "woman juggling", listOf("juggling", "multitask", "woman")),
    EmojiEntry("🧘", "person in lotus position", listOf("meditation", "person in lotus position", "yoga", "serenity")),
    EmojiEntry("🧘‍♂️", "man in lotus position", listOf("man in lotus position", "meditation", "yoga")),
    EmojiEntry("🧘‍♀️", "woman in lotus position", listOf("meditation", "woman in lotus position", "yoga")),
    EmojiEntry("🛀", "person taking bath", listOf("bath", "bathtub", "person taking bath")),
    EmojiEntry("🛌", "person in bed", listOf("hotel", "person in bed", "sleep")),
    EmojiEntry("🧑‍🤝‍🧑", "people holding hands", listOf("couple", "hand", "hold", "holding hands", "people holding hands", "person")),
    EmojiEntry("👭", "women holding hands", listOf("couple", "hand", "holding hands", "women", "women holding hands")),
    EmojiEntry("👫", "woman and man holding hands", listOf("couple", "hand", "hold", "holding hands", "man", "woman", "woman and man holding hands")),
    EmojiEntry("👬", "men holding hands", listOf("couple", "Gemini", "holding hands", "man", "men", "men holding hands", "twins", "zodiac")),
    EmojiEntry("💏", "kiss", listOf("couple", "kiss")),
    EmojiEntry("👩‍❤️‍💋‍👨", "kiss: woman, man", listOf("couple", "kiss", "man", "woman")),
    EmojiEntry("👨‍❤️‍💋‍👨", "kiss: man, man", listOf("couple", "kiss", "man")),
    EmojiEntry("👩‍❤️‍💋‍👩", "kiss: woman, woman", listOf("couple", "kiss", "woman")),
    EmojiEntry("💑", "couple with heart", listOf("couple", "couple with heart", "love")),
    EmojiEntry("👩‍❤️‍👨", "couple with heart: woman, man", listOf("couple", "couple with heart", "love", "man", "woman")),
    EmojiEntry("👨‍❤️‍👨", "couple with heart: man, man", listOf("couple", "couple with heart", "love", "man")),
    EmojiEntry("👩‍❤️‍👩", "couple with heart: woman, woman", listOf("couple", "couple with heart", "love", "woman")),
    EmojiEntry("👪", "family", listOf("family")),
    EmojiEntry("👨‍👩‍👦", "family: man, woman, boy", listOf("boy", "family", "man", "woman")),
    EmojiEntry("👨‍👩‍👧", "family: man, woman, girl", listOf("family", "girl", "man", "woman")),
    EmojiEntry("👨‍👩‍👧‍👦", "family: man, woman, girl, boy", listOf("boy", "family", "girl", "man", "woman")),
    EmojiEntry("👨‍👩‍👦‍👦", "family: man, woman, boy, boy", listOf("boy", "family", "man", "woman")),
    EmojiEntry("👨‍👩‍👧‍👧", "family: man, woman, girl, girl", listOf("family", "girl", "man", "woman")),
    EmojiEntry("👨‍👨‍👦", "family: man, man, boy", listOf("boy", "family", "man")),
    EmojiEntry("👨‍👨‍👧", "family: man, man, girl", listOf("family", "girl", "man")),
    EmojiEntry("👨‍👨‍👧‍👦", "family: man, man, girl, boy", listOf("boy", "family", "girl", "man")),
    EmojiEntry("👨‍👨‍👦‍👦", "family: man, man, boy, boy", listOf("boy", "family", "man")),
    EmojiEntry("👨‍👨‍👧‍👧", "family: man, man, girl, girl", listOf("family", "girl", "man")),
    EmojiEntry("👩‍👩‍👦", "family: woman, woman, boy", listOf("boy", "family", "woman")),
    EmojiEntry("👩‍👩‍👧", "family: woman, woman, girl", listOf("family", "girl", "woman")),
    EmojiEntry("👩‍👩‍👧‍👦", "family: woman, woman, girl, boy", listOf("boy", "family", "girl", "woman")),
    EmojiEntry("👩‍👩‍👦‍👦", "family: woman, woman, boy, boy", listOf("boy", "family", "woman")),
    EmojiEntry("👩‍👩‍👧‍👧", "family: woman, woman, girl, girl", listOf("family", "girl", "woman")),
    EmojiEntry("👨‍👦", "family: man, boy", listOf("boy", "family", "man")),
    EmojiEntry("👨‍👦‍👦", "family: man, boy, boy", listOf("boy", "family", "man")),
    EmojiEntry("👨‍👧", "family: man, girl", listOf("family", "girl", "man")),
    EmojiEntry("👨‍👧‍👦", "family: man, girl, boy", listOf("boy", "family", "girl", "man")),
    EmojiEntry("👨‍👧‍👧", "family: man, girl, girl", listOf("family", "girl", "man")),
    EmojiEntry("👩‍👦", "family: woman, boy", listOf("boy", "family", "woman")),
    EmojiEntry("👩‍👦‍👦", "family: woman, boy, boy", listOf("boy", "family", "woman")),
    EmojiEntry("👩‍👧", "family: woman, girl", listOf("family", "girl", "woman")),
    EmojiEntry("👩‍👧‍👦", "family: woman, girl, boy", listOf("boy", "family", "girl", "woman")),
    EmojiEntry("👩‍👧‍👧", "family: woman, girl, girl", listOf("family", "girl", "woman")),
    EmojiEntry("🗣", "speaking head", listOf("face", "head", "silhouette", "speak", "speaking")),
    EmojiEntry("👤", "bust in silhouette", listOf("bust", "bust in silhouette", "silhouette")),
    EmojiEntry("👥", "busts in silhouette", listOf("bust", "busts in silhouette", "silhouette")),
    EmojiEntry("🫂", "people hugging", listOf("goodbye", "hello", "hug", "people hugging", "thanks")),
    EmojiEntry("👣", "footprints", listOf("clothing", "footprint", "footprints", "print")),
    EmojiEntry("🦰", "red hair", listOf("ginger", "red hair", "redhead")),
    EmojiEntry("🦱", "curly hair", listOf("afro", "curly", "curly hair", "ringlets")),
    EmojiEntry("🦳", "white hair", listOf("gray", "hair", "old", "white")),
    EmojiEntry("🦲", "bald", listOf("bald", "chemotherapy", "hairless", "no hair", "shaven")),
    EmojiEntry("🐵", "monkey face", listOf("face", "monkey")),
    EmojiEntry("🐒", "monkey", listOf("monkey")),
    EmojiEntry("🦍", "gorilla", listOf("gorilla")),
    EmojiEntry("🦧", "orangutan", listOf("ape", "orangutan")),
    EmojiEntry("🐶", "dog face", listOf("dog", "face", "pet")),
    EmojiEntry("🐕", "dog", listOf("dog", "pet")),
    EmojiEntry("🦮", "guide dog", listOf("accessibility", "blind", "guide", "guide dog")),
    EmojiEntry("🐕‍🦺", "service dog", listOf("accessibility", "assistance", "dog", "service")),
    EmojiEntry("🐩", "poodle", listOf("dog", "poodle")),
    EmojiEntry("🐺", "wolf", listOf("face", "wolf")),
    EmojiEntry("🦊", "fox", listOf("face", "fox")),
    EmojiEntry("🦝", "raccoon", listOf("curious", "raccoon", "sly")),
    EmojiEntry("🐱", "cat face", listOf("cat", "face", "pet")),
    EmojiEntry("🐈", "cat", listOf("cat", "pet")),
    EmojiEntry("🐈‍⬛", "black cat", listOf("black", "cat", "unlucky")),
    EmojiEntry("🦁", "lion", listOf("face", "Leo", "lion", "zodiac")),
    EmojiEntry("🐯", "tiger face", listOf("face", "tiger")),
    EmojiEntry("🐅", "tiger", listOf("tiger")),
    EmojiEntry("🐆", "leopard", listOf("leopard")),
    EmojiEntry("🐴", "horse face", listOf("face", "horse")),
    EmojiEntry("🐎", "horse", listOf("equestrian", "horse", "racehorse", "racing")),
    EmojiEntry("🦄", "unicorn", listOf("face", "unicorn")),
    EmojiEntry("🦓", "zebra", listOf("stripe", "zebra")),
    EmojiEntry("🦌", "deer", listOf("deer")),
    EmojiEntry("🦬", "bison", listOf("bison", "buffalo", "herd", "wisent")),
    EmojiEntry("🐮", "cow face", listOf("cow", "face")),
    EmojiEntry("🐂", "ox", listOf("bull", "ox", "Taurus", "zodiac")),
    EmojiEntry("🐃", "water buffalo", listOf("buffalo", "water")),
    EmojiEntry("🐄", "cow", listOf("cow")),
    EmojiEntry("🐷", "pig face", listOf("face", "pig")),
    EmojiEntry("🐖", "pig", listOf("pig", "sow")),
    EmojiEntry("🐗", "boar", listOf("boar", "pig")),
    EmojiEntry("🐽", "pig nose", listOf("face", "nose", "pig")),
    EmojiEntry("🐏", "ram", listOf("Aries", "male", "ram", "sheep", "zodiac")),
    EmojiEntry("🐑", "ewe", listOf("ewe", "female", "sheep")),
    EmojiEntry("🐐", "goat", listOf("Capricorn", "goat", "zodiac")),
    EmojiEntry("🐪", "camel", listOf("camel", "dromedary", "hump")),
    EmojiEntry("🐫", "two-hump camel", listOf("bactrian", "camel", "hump", "two-hump camel")),
    EmojiEntry("🦙", "llama", listOf("alpaca", "guanaco", "llama", "vicuña", "wool")),
    EmojiEntry("🦒", "giraffe", listOf("giraffe", "spots")),
    EmojiEntry("🐘", "elephant", listOf("elephant")),
    EmojiEntry("🦣", "mammoth", listOf("extinction", "large", "mammoth", "tusk", "woolly")),
    EmojiEntry("🦏", "rhinoceros", listOf("rhinoceros")),
    EmojiEntry("🦛", "hippopotamus", listOf("hippo", "hippopotamus")),
    EmojiEntry("🐭", "mouse face", listOf("face", "mouse")),
    EmojiEntry("🐁", "mouse", listOf("mouse")),
    EmojiEntry("🐀", "rat", listOf("rat")),
    EmojiEntry("🐹", "hamster", listOf("face", "hamster", "pet")),
    EmojiEntry("🐰", "rabbit face", listOf("bunny", "face", "pet", "rabbit")),
    EmojiEntry("🐇", "rabbit", listOf("bunny", "pet", "rabbit")),
    EmojiEntry("🐿", "chipmunk", listOf("chipmunk", "squirrel")),
    EmojiEntry("🦫", "beaver", listOf("beaver", "dam")),
    EmojiEntry("🦔", "hedgehog", listOf("hedgehog", "spiny")),
    EmojiEntry("🦇", "bat", listOf("bat", "vampire")),
    EmojiEntry("🐻", "bear", listOf("bear", "face")),
    EmojiEntry("🐻‍❄️", "polar bear", listOf("arctic", "bear", "polar bear", "white")),
    EmojiEntry("🐨", "koala", listOf("bear", "koala")),
    EmojiEntry("🐼", "panda", listOf("face", "panda")),
    EmojiEntry("🦥", "sloth", listOf("lazy", "sloth", "slow")),
    EmojiEntry("🦦", "otter", listOf("fishing", "otter", "playful")),
    EmojiEntry("🦨", "skunk", listOf("skunk", "stink")),
    EmojiEntry("🦘", "kangaroo", listOf("Australia", "joey", "jump", "kangaroo", "marsupial")),
    EmojiEntry("🦡", "badger", listOf("badger", "honey badger", "pester")),
    EmojiEntry("🐾", "paw prints", listOf("feet", "paw", "paw prints", "print")),
    EmojiEntry("🦃", "turkey", listOf("bird", "turkey")),
    EmojiEntry("🐔", "chicken", listOf("bird", "chicken")),
    EmojiEntry("🐓", "rooster", listOf("bird", "rooster")),
    EmojiEntry("🐣", "hatching chick", listOf("baby", "bird", "chick", "hatching")),
    EmojiEntry("🐤", "baby chick", listOf("baby", "bird", "chick")),
    EmojiEntry("🐥", "front-facing baby chick", listOf("baby", "bird", "chick", "front-facing baby chick")),
    EmojiEntry("🐦", "bird", listOf("bird")),
    EmojiEntry("🐧", "penguin", listOf("bird", "penguin")),
    EmojiEntry("🕊", "dove", listOf("bird", "dove", "fly", "peace")),
    EmojiEntry("🦅", "eagle", listOf("bird", "eagle")),
    EmojiEntry("🦆", "duck", listOf("bird", "duck")),
    EmojiEntry("🦢", "swan", listOf("bird", "cygnet", "swan", "ugly duckling")),
    EmojiEntry("🦉", "owl", listOf("bird", "owl", "wise")),
    EmojiEntry("🦤", "dodo", listOf("dodo", "extinction", "large", "Mauritius")),
    EmojiEntry("🪶", "feather", listOf("bird", "feather", "flight", "light", "plumage")),
    EmojiEntry("🦩", "flamingo", listOf("flamboyant", "flamingo", "tropical")),
    EmojiEntry("🦚", "peacock", listOf("bird", "ostentatious", "peacock", "peahen", "proud")),
    EmojiEntry("🦜", "parrot", listOf("bird", "parrot", "pirate", "talk")),
    EmojiEntry("🐸", "frog", listOf("face", "frog")),
    EmojiEntry("🐊", "crocodile", listOf("crocodile")),
    EmojiEntry("🐢", "turtle", listOf("terrapin", "tortoise", "turtle")),
    EmojiEntry("🦎", "lizard", listOf("lizard", "reptile")),
    EmojiEntry("🐍", "snake", listOf("bearer", "Ophiuchus", "serpent", "snake", "zodiac")),
    EmojiEntry("🐲", "dragon face", listOf("dragon", "face", "fairy tale")),
    EmojiEntry("🐉", "dragon", listOf("dragon", "fairy tale")),
    EmojiEntry("🦕", "sauropod", listOf("brachiosaurus", "brontosaurus", "diplodocus", "sauropod")),
    EmojiEntry("🦖", "T-Rex", listOf("T-Rex", "Tyrannosaurus Rex")),
)
