package com.zacksimpson.emojis

// Auto-generated from the RN app's utils/emojiData.ts via scripts/convert-emoji-index.js — do not hand-edit.
// Part 9/13 of EMOJI_INDEX, split across files so each file's <clinit> stays under the JVM's 64KB method size limit.
internal val EMOJI_INDEX_PART_8: List<EmojiEntry> = listOf(
    EmojiEntry("🏷", "label", listOf("label")),
    EmojiEntry("💰", "money bag", listOf("bag", "dollar", "money", "moneybag")),
    EmojiEntry("🪙", "coin", listOf("coin", "gold", "metal", "money", "silver", "treasure")),
    EmojiEntry("💴", "yen banknote", listOf("banknote", "bill", "currency", "money", "note", "yen")),
    EmojiEntry("💵", "dollar banknote", listOf("banknote", "bill", "currency", "dollar", "money", "note")),
    EmojiEntry("💶", "euro banknote", listOf("banknote", "bill", "currency", "euro", "money", "note")),
    EmojiEntry("💷", "pound banknote", listOf("banknote", "bill", "currency", "money", "note", "pound")),
    EmojiEntry("💸", "money with wings", listOf("banknote", "bill", "fly", "money", "money with wings", "wings")),
    EmojiEntry("💳", "credit card", listOf("card", "credit", "money")),
    EmojiEntry("🧾", "receipt", listOf("accounting", "bookkeeping", "evidence", "proof", "receipt")),
    EmojiEntry("💹", "chart increasing with yen", listOf("chart", "chart increasing with yen", "graph", "growth", "money", "yen")),
    EmojiEntry("✉", "envelope", listOf("email", "envelope", "letter")),
    EmojiEntry("📧", "e-mail", listOf("e-mail", "email", "letter", "mail")),
    EmojiEntry("📨", "incoming envelope", listOf("e-mail", "email", "envelope", "incoming", "letter", "receive")),
    EmojiEntry("📩", "envelope with arrow", listOf("arrow", "e-mail", "email", "envelope", "envelope with arrow", "outgoing")),
    EmojiEntry("📤", "outbox tray", listOf("box", "letter", "mail", "outbox", "sent", "tray")),
    EmojiEntry("📥", "inbox tray", listOf("box", "inbox", "letter", "mail", "receive", "tray")),
    EmojiEntry("📦", "package", listOf("box", "package", "parcel")),
    EmojiEntry("📫", "closed mailbox with raised flag", listOf("closed", "closed mailbox with raised flag", "mail", "mailbox", "postbox")),
    EmojiEntry("📪", "closed mailbox with lowered flag", listOf("closed", "closed mailbox with lowered flag", "lowered", "mail", "mailbox", "postbox")),
    EmojiEntry("📬", "open mailbox with raised flag", listOf("mail", "mailbox", "open", "open mailbox with raised flag", "postbox")),
    EmojiEntry("📭", "open mailbox with lowered flag", listOf("lowered", "mail", "mailbox", "open", "open mailbox with lowered flag", "postbox")),
    EmojiEntry("📮", "postbox", listOf("mail", "mailbox", "postbox")),
    EmojiEntry("🗳", "ballot box with ballot", listOf("ballot", "ballot box with ballot", "box")),
    EmojiEntry("✏", "pencil", listOf("pencil")),
    EmojiEntry("✒", "black nib", listOf("black nib", "nib", "pen")),
    EmojiEntry("🖋", "fountain pen", listOf("fountain", "pen")),
    EmojiEntry("🖊", "pen", listOf("ballpoint", "pen")),
    EmojiEntry("🖌", "paintbrush", listOf("paintbrush", "painting")),
    EmojiEntry("🖍", "crayon", listOf("crayon")),
    EmojiEntry("📝", "memo", listOf("memo", "pencil")),
    EmojiEntry("💼", "briefcase", listOf("briefcase")),
    EmojiEntry("📁", "file folder", listOf("file", "folder")),
    EmojiEntry("📂", "open file folder", listOf("file", "folder", "open")),
    EmojiEntry("🗂", "card index dividers", listOf("card", "dividers", "index")),
    EmojiEntry("📅", "calendar", listOf("calendar", "date")),
    EmojiEntry("📆", "tear-off calendar", listOf("calendar", "tear-off calendar")),
    EmojiEntry("🗒", "spiral notepad", listOf("note", "pad", "spiral", "spiral notepad")),
    EmojiEntry("🗓", "spiral calendar", listOf("calendar", "pad", "spiral")),
    EmojiEntry("📇", "card index", listOf("card", "index", "rolodex")),
    EmojiEntry("📈", "chart increasing", listOf("chart", "chart increasing", "graph", "growth", "trend", "upward")),
    EmojiEntry("📉", "chart decreasing", listOf("chart", "chart decreasing", "down", "graph", "trend")),
    EmojiEntry("📊", "bar chart", listOf("bar", "chart", "graph")),
    EmojiEntry("📋", "clipboard", listOf("clipboard")),
    EmojiEntry("📌", "pushpin", listOf("pin", "pushpin")),
    EmojiEntry("📍", "round pushpin", listOf("pin", "pushpin", "round pushpin")),
    EmojiEntry("📎", "paperclip", listOf("paperclip")),
    EmojiEntry("🖇", "linked paperclips", listOf("link", "linked paperclips", "paperclip")),
    EmojiEntry("📏", "straight ruler", listOf("ruler", "straight edge", "straight ruler")),
    EmojiEntry("📐", "triangular ruler", listOf("ruler", "set", "triangle", "triangular ruler")),
    EmojiEntry("✂", "scissors", listOf("cutting", "scissors", "tool")),
    EmojiEntry("🗃", "card file box", listOf("box", "card", "file")),
    EmojiEntry("🗄", "file cabinet", listOf("cabinet", "file", "filing")),
    EmojiEntry("🗑", "wastebasket", listOf("wastebasket")),
    EmojiEntry("🔒", "locked", listOf("closed", "locked")),
    EmojiEntry("🔓", "unlocked", listOf("lock", "open", "unlock", "unlocked")),
    EmojiEntry("🔏", "locked with pen", listOf("ink", "lock", "locked with pen", "nib", "pen", "privacy")),
    EmojiEntry("🔐", "locked with key", listOf("closed", "key", "lock", "locked with key", "secure")),
    EmojiEntry("🔑", "key", listOf("key", "lock", "password")),
    EmojiEntry("🗝", "old key", listOf("clue", "key", "lock", "old")),
    EmojiEntry("🔨", "hammer", listOf("hammer", "tool")),
    EmojiEntry("🪓", "axe", listOf("axe", "chop", "hatchet", "split", "wood")),
    EmojiEntry("⛏", "pick", listOf("mining", "pick", "tool")),
    EmojiEntry("⚒", "hammer and pick", listOf("hammer", "hammer and pick", "pick", "tool")),
    EmojiEntry("🛠", "hammer and wrench", listOf("hammer", "hammer and wrench", "spanner", "tool", "wrench")),
    EmojiEntry("🗡", "dagger", listOf("dagger", "knife", "weapon")),
    EmojiEntry("⚔", "crossed swords", listOf("crossed", "swords", "weapon")),
    EmojiEntry("🔫", "water pistol", listOf("gun", "handgun", "pistol", "revolver", "tool", "water", "weapon")),
    EmojiEntry("🪃", "boomerang", listOf("australia", "boomerang", "rebound", "repercussion")),
    EmojiEntry("🏹", "bow and arrow", listOf("archer", "arrow", "bow", "bow and arrow", "Sagittarius", "zodiac")),
    EmojiEntry("🛡", "shield", listOf("shield", "weapon")),
    EmojiEntry("🪚", "carpentry saw", listOf("carpenter", "carpentry saw", "lumber", "saw", "tool")),
    EmojiEntry("🔧", "wrench", listOf("spanner", "tool", "wrench")),
    EmojiEntry("🪛", "screwdriver", listOf("screw", "screwdriver", "tool")),
    EmojiEntry("🔩", "nut and bolt", listOf("bolt", "nut", "nut and bolt", "tool")),
    EmojiEntry("⚙", "gear", listOf("cog", "cogwheel", "gear", "tool")),
    EmojiEntry("🗜", "clamp", listOf("clamp", "compress", "tool", "vice")),
    EmojiEntry("⚖", "balance scale", listOf("balance", "justice", "Libra", "scale", "zodiac")),
    EmojiEntry("🦯", "white cane", listOf("accessibility", "blind", "white cane")),
    EmojiEntry("🔗", "link", listOf("link")),
    EmojiEntry("⛓", "chains", listOf("chain", "chains")),
    EmojiEntry("🪝", "hook", listOf("catch", "crook", "curve", "ensnare", "hook", "selling point")),
    EmojiEntry("🧰", "toolbox", listOf("chest", "mechanic", "tool", "toolbox")),
    EmojiEntry("🧲", "magnet", listOf("attraction", "horseshoe", "magnet", "magnetic")),
    EmojiEntry("🪜", "ladder", listOf("climb", "ladder", "rung", "step")),
    EmojiEntry("⚗", "alembic", listOf("alembic", "chemistry", "tool")),
    EmojiEntry("🧪", "test tube", listOf("chemist", "chemistry", "experiment", "lab", "science", "test tube")),
    EmojiEntry("🧫", "petri dish", listOf("bacteria", "biologist", "biology", "culture", "lab", "petri dish")),
    EmojiEntry("🧬", "dna", listOf("biologist", "dna", "evolution", "gene", "genetics", "life")),
    EmojiEntry("🔬", "microscope", listOf("microscope", "science", "tool")),
    EmojiEntry("🔭", "telescope", listOf("science", "telescope", "tool")),
    EmojiEntry("📡", "satellite antenna", listOf("antenna", "dish", "satellite")),
    EmojiEntry("💉", "syringe", listOf("medicine", "needle", "shot", "sick", "syringe")),
    EmojiEntry("🩸", "drop of blood", listOf("bleed", "blood donation", "drop of blood", "injury", "medicine", "menstruation")),
    EmojiEntry("💊", "pill", listOf("doctor", "medicine", "pill", "sick")),
    EmojiEntry("🩹", "adhesive bandage", listOf("adhesive bandage", "bandage")),
    EmojiEntry("🩺", "stethoscope", listOf("doctor", "heart", "medicine", "stethoscope")),
    EmojiEntry("🚪", "door", listOf("door")),
    EmojiEntry("🛗", "elevator", listOf("accessibility", "elevator", "hoist", "lift")),
    EmojiEntry("🪞", "mirror", listOf("mirror", "reflection", "reflector", "speculum")),
    EmojiEntry("🪟", "window", listOf("frame", "fresh air", "opening", "transparent", "view", "window")),
    EmojiEntry("🛏", "bed", listOf("bed", "hotel", "sleep")),
    EmojiEntry("🛋", "couch and lamp", listOf("couch", "couch and lamp", "hotel", "lamp")),
    EmojiEntry("🪑", "chair", listOf("chair", "seat", "sit")),
    EmojiEntry("🚽", "toilet", listOf("toilet")),
    EmojiEntry("🪠", "plunger", listOf("force cup", "plumber", "plunger", "suction", "toilet")),
    EmojiEntry("🚿", "shower", listOf("shower", "water")),
    EmojiEntry("🛁", "bathtub", listOf("bath", "bathtub")),
    EmojiEntry("🪤", "mouse trap", listOf("bait", "mouse trap", "mousetrap", "snare", "trap")),
    EmojiEntry("🪒", "razor", listOf("razor", "sharp", "shave")),
    EmojiEntry("🧴", "lotion bottle", listOf("lotion", "lotion bottle", "moisturizer", "shampoo", "sunscreen")),
    EmojiEntry("🧷", "safety pin", listOf("diaper", "punk rock", "safety pin")),
    EmojiEntry("🧹", "broom", listOf("broom", "cleaning", "sweeping", "witch")),
    EmojiEntry("🧺", "basket", listOf("basket", "farming", "laundry", "picnic")),
    EmojiEntry("🧻", "roll of paper", listOf("paper towels", "roll of paper", "toilet paper")),
    EmojiEntry("🪣", "bucket", listOf("bucket", "cask", "pail", "vat")),
    EmojiEntry("🧼", "soap", listOf("bar", "bathing", "cleaning", "lather", "soap", "soapdish")),
    EmojiEntry("🪥", "toothbrush", listOf("bathroom", "brush", "clean", "dental", "hygiene", "teeth", "toothbrush")),
    EmojiEntry("🧽", "sponge", listOf("absorbing", "cleaning", "porous", "sponge")),
    EmojiEntry("🧯", "fire extinguisher", listOf("extinguish", "fire", "fire extinguisher", "quench")),
    EmojiEntry("🛒", "shopping cart", listOf("cart", "shopping", "trolley")),
    EmojiEntry("🚬", "cigarette", listOf("cigarette", "smoking")),
    EmojiEntry("⚰", "coffin", listOf("coffin", "death")),
    EmojiEntry("🪦", "headstone", listOf("cemetery", "grave", "graveyard", "headstone", "tombstone")),
    EmojiEntry("⚱", "funeral urn", listOf("ashes", "death", "funeral", "urn")),
    EmojiEntry("🗿", "moai", listOf("face", "moai", "moyai", "statue")),
    EmojiEntry("🪧", "placard", listOf("demonstration", "picket", "placard", "protest", "sign")),
    EmojiEntry("🏧", "ATM sign", listOf("atm", "ATM sign", "automated", "bank", "teller")),
    EmojiEntry("🚮", "litter in bin sign", listOf("litter", "litter bin", "litter in bin sign")),
    EmojiEntry("🚰", "potable water", listOf("drinking", "potable", "water")),
    EmojiEntry("♿", "wheelchair symbol", listOf("access", "wheelchair symbol")),
    EmojiEntry("🚹", "mens room", listOf("lavatory", "man", "mens room", "restroom", "wc")),
    EmojiEntry("🚺", "womens room", listOf("lavatory", "restroom", "wc", "woman", "womens room")),
    EmojiEntry("🚻", "restroom", listOf("lavatory", "restroom", "WC")),
    EmojiEntry("🚼", "baby symbol", listOf("baby", "baby symbol", "changing")),
    EmojiEntry("🚾", "water closet", listOf("closet", "lavatory", "restroom", "water", "wc")),
    EmojiEntry("🛂", "passport control", listOf("control", "passport")),
    EmojiEntry("🛃", "customs", listOf("customs")),
    EmojiEntry("🛄", "baggage claim", listOf("baggage", "claim")),
    EmojiEntry("🛅", "left luggage", listOf("baggage", "left luggage", "locker", "luggage")),
    EmojiEntry("⚠", "warning", listOf("warning")),
    EmojiEntry("🚸", "children crossing", listOf("child", "children crossing", "crossing", "pedestrian", "traffic")),
    EmojiEntry("⛔", "no entry", listOf("entry", "forbidden", "no", "not", "prohibited", "traffic")),
    EmojiEntry("🚫", "prohibited", listOf("entry", "forbidden", "no", "not", "prohibited")),
    EmojiEntry("🚳", "no bicycles", listOf("bicycle", "bike", "forbidden", "no", "no bicycles", "prohibited")),
    EmojiEntry("🚭", "no smoking", listOf("forbidden", "no", "not", "prohibited", "smoking")),
    EmojiEntry("🚯", "no littering", listOf("forbidden", "litter", "no", "no littering", "not", "prohibited")),
    EmojiEntry("🚱", "non-potable water", listOf("non-drinking", "non-potable", "water")),
    EmojiEntry("🚷", "no pedestrians", listOf("forbidden", "no", "no pedestrians", "not", "pedestrian", "prohibited")),
    EmojiEntry("📵", "no mobile phones", listOf("cell", "forbidden", "mobile", "no", "no mobile phones", "phone")),
)
