[tool]
id          = "com.zacksimpson.emojis"
label       = "Emojis"
versionCode = 1
versionName = "0.1.0"
permissions = []
# change if you run this on an LP3!
# serverPackage = "com.lightos"
serverPackage = "com.thelightphone.sdk.emulator"
